import type { StorefrontLocale } from "@/contexts/LocaleContext";

type AccountCopy = {
  loading: string;
  back: string;
  title: string;
  lead: string;
  welcome: string;
  guestLead: string;
  login: string;
  register: string;
  whyTitle: string;
  benefits: { ordersTitle: string; ordersText: string; favoritesTitle: string; favoritesText: string; settingsTitle: string; settingsText: string };
  customerFallback: string;
  ordersTitle: string;
  ordersText: string;
  favoritesTitle: string;
  favoritesText: string;
  settingsTitle: string;
  settingsText: string;
  adminTitle: string;
  adminText: string;
  logoutTitle: string;
  logoutText: string;
  tipTitle: string;
  tipAuthenticated: string;
  tipGuest: string;
};

const copy: Record<StorefrontLocale, AccountCopy> = {
  fr: { loading: "Chargement…", back: "Retour à l’accueil", title: "Mon compte", lead: "Gérez votre profil, vos commandes et vos préférences.", welcome: "Bienvenue !", guestLead: "Connectez-vous pour accéder à votre compte.", login: "Se connecter", register: "Créer un compte", whyTitle: "Pourquoi créer un compte ?", benefits: { ordersTitle: "Suivi de commandes", ordersText: "Consultez l’historique de vos achats.", favoritesTitle: "Favoris", favoritesText: "Sauvegardez vos produits préférés.", settingsTitle: "Paramètres", settingsText: "Gérez vos informations personnelles." }, customerFallback: "Client MAZIGHO", ordersTitle: "Mes commandes", ordersText: "Consultez l’historique de vos achats.", favoritesTitle: "Mes favoris", favoritesText: "Accédez à vos produits préférés.", settingsTitle: "Paramètres", settingsText: "Modifiez vos informations personnelles.", adminTitle: "Administration", adminText: "Gérer la boutique, les produits et les commandes.", logoutTitle: "Déconnexion", logoutText: "Quitter votre compte.", tipTitle: "Astuce", tipAuthenticated: "Vous êtes connecté. Vous pouvez accéder à vos services MAZIGHO.", tipGuest: "Créez un compte pour accéder au suivi, à l’historique et à votre liste de favoris." },
  de: { loading: "Wird geladen…", back: "Zurück zur Startseite", title: "Mein Konto", lead: "Verwalten Sie Ihr Profil, Ihre Bestellungen und Ihre Einstellungen.", welcome: "Willkommen!", guestLead: "Melden Sie sich an, um auf Ihr Konto zuzugreifen.", login: "Anmelden", register: "Konto erstellen", whyTitle: "Warum ein Konto erstellen?", benefits: { ordersTitle: "Bestellübersicht", ordersText: "Sehen Sie Ihre Kaufhistorie ein.", favoritesTitle: "Favoriten", favoritesText: "Speichern Sie Ihre bevorzugten Produkte.", settingsTitle: "Einstellungen", settingsText: "Verwalten Sie Ihre persönlichen Daten." }, customerFallback: "MAZIGHO-Kunde", ordersTitle: "Meine Bestellungen", ordersText: "Sehen Sie Ihre Kaufhistorie ein.", favoritesTitle: "Meine Favoriten", favoritesText: "Rufen Sie Ihre bevorzugten Produkte auf.", settingsTitle: "Einstellungen", settingsText: "Ändern Sie Ihre persönlichen Daten.", adminTitle: "Verwaltung", adminText: "Shop, Produkte und Bestellungen verwalten.", logoutTitle: "Abmelden", logoutText: "Konto verlassen.", tipTitle: "Hinweis", tipAuthenticated: "Sie sind angemeldet. Sie können auf Ihre MAZIGHO-Dienste zugreifen.", tipGuest: "Erstellen Sie ein Konto für Übersicht, Historie und Ihre Favoritenliste." },
  it: { loading: "Caricamento…", back: "Torna alla home", title: "Il mio account", lead: "Gestisci il profilo, gli ordini e le preferenze.", welcome: "Benvenuto!", guestLead: "Accedi per entrare nel tuo account.", login: "Accedi", register: "Crea un account", whyTitle: "Perché creare un account?", benefits: { ordersTitle: "Monitoraggio ordini", ordersText: "Consulta la cronologia degli acquisti.", favoritesTitle: "Preferiti", favoritesText: "Salva i prodotti preferiti.", settingsTitle: "Impostazioni", settingsText: "Gestisci i dati personali." }, customerFallback: "Cliente MAZIGHO", ordersTitle: "I miei ordini", ordersText: "Consulta la cronologia degli acquisti.", favoritesTitle: "I miei preferiti", favoritesText: "Accedi ai prodotti preferiti.", settingsTitle: "Impostazioni", settingsText: "Modifica i dati personali.", adminTitle: "Amministrazione", adminText: "Gestisci negozio, prodotti e ordini.", logoutTitle: "Esci", logoutText: "Esci dal tuo account.", tipTitle: "Suggerimento", tipAuthenticated: "Hai effettuato l’accesso. Puoi usare i servizi MAZIGHO.", tipGuest: "Crea un account per accedere a monitoraggio, cronologia e preferiti." },
  en: { loading: "Loading…", back: "Back to home", title: "My account", lead: "Manage your profile, orders and preferences.", welcome: "Welcome!", guestLead: "Sign in to access your account.", login: "Sign in", register: "Create an account", whyTitle: "Why create an account?", benefits: { ordersTitle: "Order tracking", ordersText: "View your purchase history.", favoritesTitle: "Favorites", favoritesText: "Save your preferred products.", settingsTitle: "Settings", settingsText: "Manage your personal information." }, customerFallback: "MAZIGHO customer", ordersTitle: "My orders", ordersText: "View your purchase history.", favoritesTitle: "My favorites", favoritesText: "Access your preferred products.", settingsTitle: "Settings", settingsText: "Update your personal information.", adminTitle: "Administration", adminText: "Manage the store, products and orders.", logoutTitle: "Sign out", logoutText: "Leave your account.", tipTitle: "Tip", tipAuthenticated: "You are signed in. You can access your MAZIGHO services.", tipGuest: "Create an account to access tracking, history and your favorites list." },
  es: { loading: "Cargando…", back: "Volver al inicio", title: "Mi cuenta", lead: "Gestiona tu perfil, pedidos y preferencias.", welcome: "¡Bienvenido!", guestLead: "Inicia sesión para acceder a tu cuenta.", login: "Iniciar sesión", register: "Crear una cuenta", whyTitle: "¿Por qué crear una cuenta?", benefits: { ordersTitle: "Seguimiento de pedidos", ordersText: "Consulta tu historial de compras.", favoritesTitle: "Favoritos", favoritesText: "Guarda tus productos preferidos.", settingsTitle: "Configuración", settingsText: "Gestiona tus datos personales." }, customerFallback: "Cliente MAZIGHO", ordersTitle: "Mis pedidos", ordersText: "Consulta tu historial de compras.", favoritesTitle: "Mis favoritos", favoritesText: "Accede a tus productos preferidos.", settingsTitle: "Configuración", settingsText: "Modifica tus datos personales.", adminTitle: "Administración", adminText: "Gestionar la tienda, productos y pedidos.", logoutTitle: "Cerrar sesión", logoutText: "Salir de tu cuenta.", tipTitle: "Consejo", tipAuthenticated: "Has iniciado sesión. Puedes acceder a tus servicios MAZIGHO.", tipGuest: "Crea una cuenta para acceder al seguimiento, historial y lista de favoritos." },
  nl: { loading: "Laden…", back: "Terug naar home", title: "Mijn account", lead: "Beheer uw profiel, bestellingen en voorkeuren.", welcome: "Welkom!", guestLead: "Meld u aan om uw account te openen.", login: "Aanmelden", register: "Account aanmaken", whyTitle: "Waarom een account aanmaken?", benefits: { ordersTitle: "Bestellingen volgen", ordersText: "Bekijk uw aankoopgeschiedenis.", favoritesTitle: "Favorieten", favoritesText: "Bewaar uw favoriete producten.", settingsTitle: "Instellingen", settingsText: "Beheer uw persoonlijke gegevens." }, customerFallback: "MAZIGHO-klant", ordersTitle: "Mijn bestellingen", ordersText: "Bekijk uw aankoopgeschiedenis.", favoritesTitle: "Mijn favorieten", favoritesText: "Open uw favoriete producten.", settingsTitle: "Instellingen", settingsText: "Wijzig uw persoonlijke gegevens.", adminTitle: "Beheer", adminText: "Beheer de winkel, producten en bestellingen.", logoutTitle: "Afmelden", logoutText: "Uw account verlaten.", tipTitle: "Tip", tipAuthenticated: "U bent aangemeld. U kunt uw MAZIGHO-diensten gebruiken.", tipGuest: "Maak een account aan voor opvolging, geschiedenis en uw favorietenlijst." },
  ar: { loading: "جارٍ التحميل…", back: "العودة إلى الرئيسية", title: "حسابي", lead: "أدر ملفك الشخصي وطلباتك وتفضيلاتك.", welcome: "مرحباً!", guestLead: "سجّل الدخول للوصول إلى حسابك.", login: "تسجيل الدخول", register: "إنشاء حساب", whyTitle: "لماذا تنشئ حساباً؟", benefits: { ordersTitle: "متابعة الطلبات", ordersText: "اطلع على سجل مشترياتك.", favoritesTitle: "المفضلة", favoritesText: "احفظ منتجاتك المفضلة.", settingsTitle: "الإعدادات", settingsText: "أدر معلوماتك الشخصية." }, customerFallback: "عميل MAZIGHO", ordersTitle: "طلباتي", ordersText: "اطلع على سجل مشترياتك.", favoritesTitle: "مفضلتي", favoritesText: "ادخل إلى منتجاتك المفضلة.", settingsTitle: "الإعدادات", settingsText: "عدّل معلوماتك الشخصية.", adminTitle: "الإدارة", adminText: "إدارة المتجر والمنتجات والطلبات.", logoutTitle: "تسجيل الخروج", logoutText: "مغادرة حسابك.", tipTitle: "معلومة", tipAuthenticated: "لقد سجّلت الدخول. يمكنك الوصول إلى خدمات MAZIGHO الخاصة بك.", tipGuest: "أنشئ حساباً للوصول إلى المتابعة والسجل وقائمة المفضلة." },
};

export function getAccountCopy(locale: StorefrontLocale): AccountCopy {
  return copy[locale] ?? copy.fr;
}
