import type { StorefrontLocale } from "@/contexts/LocaleContext";

type AccountStatusCopy = {
  back: string;
  settings: { title: string; lead: string; profileTitle: string; profileText: string; name: string; email: string; contactCta: string; securityTitle: string; securityText: string; passwordCta: string; signInCta: string };
  orders: { title: string; lead: string; emptyTitle: string; emptyText: string; shopCta: string; infoTitle: string; infoText: string };
};

const copy: Record<StorefrontLocale, AccountStatusCopy> = {
  fr: { back: "Retour à mon compte", settings: { title: "Paramètres", lead: "Consultez les informations associées à votre compte.", profileTitle: "Profil en consultation", profileText: "La modification autonome des données personnelles n’est pas encore activée. Pour demander une correction, utilisez le formulaire de contact.", name: "Nom", email: "Adresse e-mail", contactCta: "Contacter MAZIGHO", securityTitle: "Sécurité du compte", securityText: "La modification du mot de passe est disponible uniquement depuis une session connectée. Les règles de sécurité restent inchangées.", passwordCta: "Modifier le mot de passe", signInCta: "Se connecter" }, orders: { title: "Mes commandes", lead: "Consultez l’historique de vos commandes lorsqu’un parcours de commande actif sera disponible.", emptyTitle: "Aucune commande enregistrée", emptyText: "Aucune commande n’est actuellement liée à ce compte.", shopCta: "Découvrir nos produits", infoTitle: "Historique de commandes", infoText: "Les commandes, paiements, expéditions et notifications ne sont pas encore activés sur cette vitrine. Aucun suivi fictif n’est affiché." } },
  de: { back: "Zurück zu meinem Konto", settings: { title: "Einstellungen", lead: "Sehen Sie die mit Ihrem Konto verbundenen Informationen ein.", profileTitle: "Profilansicht", profileText: "Die selbstständige Änderung persönlicher Daten ist noch nicht aktiviert. Nutzen Sie für Korrekturen das Kontaktformular.", name: "Name", email: "E-Mail-Adresse", contactCta: "MAZIGHO kontaktieren", securityTitle: "Kontosicherheit", securityText: "Eine Passwortänderung ist nur in einer angemeldeten Sitzung verfügbar. Die Sicherheitsregeln bleiben unverändert.", passwordCta: "Passwort ändern", signInCta: "Anmelden" }, orders: { title: "Meine Bestellungen", lead: "Sehen Sie Ihre Bestellhistorie ein, sobald ein aktiver Bestellprozess verfügbar ist.", emptyTitle: "Keine Bestellung gespeichert", emptyText: "Derzeit ist keine Bestellung mit diesem Konto verknüpft.", shopCta: "Produkte entdecken", infoTitle: "Bestellhistorie", infoText: "Bestellungen, Zahlungen, Versand und Benachrichtigungen sind in dieser Präsentation noch nicht aktiviert. Es wird keine fiktive Nachverfolgung angezeigt." } },
  it: { back: "Torna al mio account", settings: { title: "Impostazioni", lead: "Consulta le informazioni associate al tuo account.", profileTitle: "Profilo in consultazione", profileText: "La modifica autonoma dei dati personali non è ancora attiva. Per richiedere una correzione, usa il modulo di contatto.", name: "Nome", email: "Indirizzo e-mail", contactCta: "Contatta MAZIGHO", securityTitle: "Sicurezza dell’account", securityText: "La modifica della password è disponibile solo da una sessione connessa. Le regole di sicurezza restano invariate.", passwordCta: "Modifica password", signInCta: "Accedi" }, orders: { title: "I miei ordini", lead: "Consulta la cronologia degli ordini quando sarà disponibile un percorso d’ordine attivo.", emptyTitle: "Nessun ordine registrato", emptyText: "Al momento nessun ordine è collegato a questo account.", shopCta: "Scopri i prodotti", infoTitle: "Cronologia ordini", infoText: "Ordini, pagamenti, spedizioni e notifiche non sono ancora attivi in questa vetrina. Non viene mostrato alcun tracciamento fittizio." } },
  en: { back: "Back to my account", settings: { title: "Settings", lead: "View the information associated with your account.", profileTitle: "Profile view", profileText: "Self-service editing of personal data is not enabled yet. Use the contact form to request a correction.", name: "Name", email: "Email address", contactCta: "Contact MAZIGHO", securityTitle: "Account security", securityText: "Password changes are available only from a signed-in session. Security rules remain unchanged.", passwordCta: "Change password", signInCta: "Sign in" }, orders: { title: "My orders", lead: "View your order history when an active order journey is available.", emptyTitle: "No recorded order", emptyText: "No order is currently linked to this account.", shopCta: "Discover products", infoTitle: "Order history", infoText: "Orders, payments, shipments and notifications are not yet active on this storefront. No fictitious tracking is shown." } },
  es: { back: "Volver a mi cuenta", settings: { title: "Configuración", lead: "Consulta la información asociada a tu cuenta.", profileTitle: "Perfil en consulta", profileText: "La edición autónoma de datos personales todavía no está activa. Utiliza el formulario de contacto para solicitar una corrección.", name: "Nombre", email: "Correo electrónico", contactCta: "Contactar con MAZIGHO", securityTitle: "Seguridad de la cuenta", securityText: "El cambio de contraseña solo está disponible desde una sesión iniciada. Las reglas de seguridad no cambian.", passwordCta: "Cambiar contraseña", signInCta: "Iniciar sesión" }, orders: { title: "Mis pedidos", lead: "Consulta tu historial cuando haya un recorrido de pedido activo disponible.", emptyTitle: "No hay pedidos registrados", emptyText: "Actualmente no hay pedidos vinculados a esta cuenta.", shopCta: "Descubrir productos", infoTitle: "Historial de pedidos", infoText: "Los pedidos, pagos, envíos y notificaciones aún no están activos en esta vitrina. No se muestra ningún seguimiento ficticio." } },
  nl: { back: "Terug naar mijn account", settings: { title: "Instellingen", lead: "Bekijk de informatie die aan uw account is gekoppeld.", profileTitle: "Profiel bekijken", profileText: "Zelfstandig wijzigen van persoonsgegevens is nog niet actief. Gebruik het contactformulier om een correctie te vragen.", name: "Naam", email: "E-mailadres", contactCta: "Contact opnemen met MAZIGHO", securityTitle: "Accountbeveiliging", securityText: "Wachtwoord wijzigen is alleen beschikbaar vanuit een aangemelde sessie. De veiligheidsregels blijven ongewijzigd.", passwordCta: "Wachtwoord wijzigen", signInCta: "Aanmelden" }, orders: { title: "Mijn bestellingen", lead: "Bekijk uw bestelgeschiedenis zodra er een actief besteltraject beschikbaar is.", emptyTitle: "Geen bestelling geregistreerd", emptyText: "Er is momenteel geen bestelling aan dit account gekoppeld.", shopCta: "Producten ontdekken", infoTitle: "Bestelgeschiedenis", infoText: "Bestellingen, betalingen, verzendingen en meldingen zijn nog niet actief in deze winkel. Er wordt geen fictieve tracking getoond." } },
  ar: { back: "العودة إلى حسابي", settings: { title: "الإعدادات", lead: "اطّلع على المعلومات المرتبطة بحسابك.", profileTitle: "عرض الملف الشخصي", profileText: "تعديل البيانات الشخصية ذاتياً غير مفعّل بعد. استخدم نموذج الاتصال لطلب تصحيح.", name: "الاسم", email: "البريد الإلكتروني", contactCta: "اتصل بـ MAZIGHO", securityTitle: "أمان الحساب", securityText: "تغيير كلمة المرور متاح فقط من جلسة مسجّل دخولها. تبقى قواعد الأمان دون تغيير.", passwordCta: "تغيير كلمة المرور", signInCta: "تسجيل الدخول" }, orders: { title: "طلباتي", lead: "اطّلع على سجل طلباتك عند توفر مسار طلب نشط.", emptyTitle: "لا توجد طلبات مسجلة", emptyText: "لا يوجد حالياً أي طلب مرتبط بهذا الحساب.", shopCta: "اكتشف المنتجات", infoTitle: "سجل الطلبات", infoText: "الطلبات والمدفوعات والشحن والإشعارات غير مفعلة بعد في هذه الواجهة. لا يتم عرض أي تتبع وهمي." } },
};

export function getAccountStatusCopy(locale: StorefrontLocale): AccountStatusCopy { return copy[locale] ?? copy.fr; }
