import type { StorefrontLocale } from "@/contexts/LocaleContext";

type CollectionsCopy = {
  newArrivals: { back: string; title: string; lead: string; empty: string };
  creations: { eyebrow: string; title: string; lead: string; cta: string; globalTitle: string; globalText: string; customTitle: string; customText: string; chooseEyebrow: string; collectionsTitle: string; collectionsText: string; explore: string; discoverEyebrow: string; preparingTitle: string; destination: string; deliveryPending: string; firstTitle: string; firstText: string; categories: string };
};

const copy: Record<StorefrontLocale, CollectionsCopy> = {
  fr: { newArrivals: { back: "Retour à l’accueil", title: "🆕 Nouveautés", lead: "Découvrez les nouveautés dont la livraison est confirmée vers {country}.", empty: "Aucune nouveauté n’est encore confirmée pour la livraison vers {country}." }, creations: { eyebrow: "Univers MAZIGHO", title: "Collections créatives", lead: "Des objets et vêtements portant des designs imaginés par MAZIGHO. Parcourez toutes les collections ; le coût et le délai sont confirmés pour votre destination avant toute commande.", cta: "Découvrir les collections", globalTitle: "Catalogue visible partout", globalText: "Aucune collection ne disparaît selon le pays choisi.", customTitle: "Atelier sur mesure à venir", customText: "La création par les clients sera ajoutée après un parcours de validation dédié.", chooseEyebrow: "Choisir un support", collectionsTitle: "Nos collections", collectionsText: "Chaque collection rassemble des produits distincts de la boutique fournisseurs habituelle.", explore: "Explorer", discoverEyebrow: "À découvrir", preparingTitle: "Les collections en préparation", destination: "Destination sélectionnée", deliveryPending: "Livraison à confirmer pour {country}", firstTitle: "La première collection MAZIGHO est en préparation.", firstText: "Les catégories sont déjà ouvertes à tous. Les premiers designs MAZIGHO apparaîtront seulement après contrôle du visuel, des droits de création, du prix et de la livraison.", categories: "Voir les catégories" } },
  de: { newArrivals: { back: "Zurück zur Startseite", title: "🆕 Neuheiten", lead: "Entdecken Sie Neuheiten mit bestätigter Lieferung nach {country}.", empty: "Für {country} sind noch keine Neuheiten mit bestätigter Lieferung verfügbar." }, creations: { eyebrow: "MAZIGHO-Universum", title: "Kreative Kollektionen", lead: "Objekte und Kleidung mit von MAZIGHO entworfenen Designs. Entdecken Sie alle Kollektionen; Kosten und Lieferzeit werden vor jeder Bestellung für Ihr Ziel bestätigt.", cta: "Kollektionen entdecken", globalTitle: "Katalog weltweit sichtbar", globalText: "Keine Kollektion verschwindet je nach gewähltem Land.", customTitle: "Maßatelier in Vorbereitung", customText: "Kundeneigene Kreationen werden nach einem eigenen Prüfprozess ergänzt.", chooseEyebrow: "Produkt auswählen", collectionsTitle: "Unsere Kollektionen", collectionsText: "Jede Kollektion vereint Produkte, die von der üblichen Lieferanten-Boutique getrennt sind.", explore: "Entdecken", discoverEyebrow: "Zu entdecken", preparingTitle: "Kollektionen in Vorbereitung", destination: "Gewähltes Lieferland", deliveryPending: "Lieferung nach {country} zu bestätigen", firstTitle: "Die erste MAZIGHO-Kollektion wird vorbereitet.", firstText: "Die Kategorien sind bereits für alle sichtbar. Erste MAZIGHO-Designs erscheinen erst nach Prüfung von Bild, Rechten, Preis und Lieferung.", categories: "Kategorien ansehen" } },
  it: { newArrivals: { back: "Torna alla home", title: "🆕 Novità", lead: "Scopri le novità con consegna confermata in {country}.", empty: "Nessuna novità ha ancora una consegna confermata in {country}." }, creations: { eyebrow: "Universo MAZIGHO", title: "Collezioni creative", lead: "Oggetti e abiti con design ideati da MAZIGHO. Esplora tutte le collezioni; costo e tempi sono confermati per la tua destinazione prima di ogni ordine.", cta: "Scopri le collezioni", globalTitle: "Catalogo visibile ovunque", globalText: "Nessuna collezione scompare in base al paese scelto.", customTitle: "Laboratorio su misura in arrivo", customText: "La creazione dei clienti sarà aggiunta dopo un percorso di validazione dedicato.", chooseEyebrow: "Scegli un supporto", collectionsTitle: "Le nostre collezioni", collectionsText: "Ogni collezione riunisce prodotti distinti dalla consueta boutique fornitori.", explore: "Esplora", discoverEyebrow: "Da scoprire", preparingTitle: "Collezioni in preparazione", destination: "Destinazione selezionata", deliveryPending: "Consegna da confermare in {country}", firstTitle: "La prima collezione MAZIGHO è in preparazione.", firstText: "Le categorie sono già aperte a tutti. I primi design MAZIGHO appariranno solo dopo il controllo di immagine, diritti, prezzo e consegna.", categories: "Vedi le categorie" } },
  en: { newArrivals: { back: "Back to home", title: "🆕 New arrivals", lead: "Discover new arrivals with delivery confirmed to {country}.", empty: "No new arrival with confirmed delivery to {country} is available yet." }, creations: { eyebrow: "MAZIGHO universe", title: "Creative collections", lead: "Objects and clothing featuring designs imagined by MAZIGHO. Browse every collection; cost and timing are confirmed for your destination before any order.", cta: "Discover collections", globalTitle: "Catalogue visible everywhere", globalText: "No collection disappears based on the selected country.", customTitle: "Custom workshop coming soon", customText: "Customer creation will be added after a dedicated validation journey.", chooseEyebrow: "Choose a medium", collectionsTitle: "Our collections", collectionsText: "Each collection brings together products distinct from the usual supplier shop.", explore: "Explore", discoverEyebrow: "Discover", preparingTitle: "Collections in preparation", destination: "Selected destination", deliveryPending: "Delivery to {country} to be confirmed", firstTitle: "The first MAZIGHO collection is in preparation.", firstText: "Categories are already visible to everyone. The first MAZIGHO designs will appear only after visual, rights, price and delivery checks.", categories: "View categories" } },
  es: { newArrivals: { back: "Volver al inicio", title: "🆕 Novedades", lead: "Descubre novedades con entrega confirmada en {country}.", empty: "Aún no hay novedades con entrega confirmada en {country}." }, creations: { eyebrow: "Universo MAZIGHO", title: "Colecciones creativas", lead: "Objetos y prendas con diseños imaginados por MAZIGHO. Explora todas las colecciones; el coste y el plazo se confirman para tu destino antes de cualquier pedido.", cta: "Descubrir las colecciones", globalTitle: "Catálogo visible en todo el mundo", globalText: "Ninguna colección desaparece según el país elegido.", customTitle: "Taller a medida próximamente", customText: "La creación de los clientes se añadirá tras un proceso de validación específico.", chooseEyebrow: "Elegir un soporte", collectionsTitle: "Nuestras colecciones", collectionsText: "Cada colección reúne productos distintos de la tienda habitual de proveedores.", explore: "Explorar", discoverEyebrow: "Por descubrir", preparingTitle: "Colecciones en preparación", destination: "Destino seleccionado", deliveryPending: "Entrega pendiente de confirmar en {country}", firstTitle: "La primera colección MAZIGHO está en preparación.", firstText: "Las categorías ya están abiertas a todos. Los primeros diseños MAZIGHO aparecerán solo después de revisar imagen, derechos, precio y entrega.", categories: "Ver categorías" } },
  nl: { newArrivals: { back: "Terug naar home", title: "🆕 Nieuw binnen", lead: "Ontdek nieuwigheden met bevestigde levering naar {country}.", empty: "Er is nog geen nieuw artikel met bevestigde levering naar {country}." }, creations: { eyebrow: "MAZIGHO-universum", title: "Creatieve collecties", lead: "Voorwerpen en kleding met ontwerpen van MAZIGHO. Bekijk alle collecties; kosten en termijn worden voor je bestemming bevestigd vóór elke bestelling.", cta: "Collecties ontdekken", globalTitle: "Catalogus overal zichtbaar", globalText: "Geen collectie verdwijnt volgens het gekozen land.", customTitle: "Maatwerkatelier binnenkort", customText: "Creaties door klanten worden toegevoegd na een speciaal validatietraject.", chooseEyebrow: "Kies een drager", collectionsTitle: "Onze collecties", collectionsText: "Elke collectie bevat producten die verschillen van de gebruikelijke leverancierswinkel.", explore: "Ontdekken", discoverEyebrow: "Te ontdekken", preparingTitle: "Collecties in voorbereiding", destination: "Geselecteerde bestemming", deliveryPending: "Levering naar {country} te bevestigen", firstTitle: "De eerste MAZIGHO-collectie wordt voorbereid.", firstText: "De categorieën zijn al voor iedereen zichtbaar. De eerste MAZIGHO-ontwerpen verschijnen pas na controle van beeld, rechten, prijs en levering.", categories: "Categorieën bekijken" } },
  ar: { newArrivals: { back: "العودة إلى الرئيسية", title: "🆕 وصل حديثاً", lead: "اكتشف المنتجات الجديدة التي تم تأكيد توصيلها إلى {country}.", empty: "لا توجد حتى الآن منتجات جديدة مع توصيل مؤكد إلى {country}." }, creations: { eyebrow: "عالم MAZIGHO", title: "مجموعات إبداعية", lead: "أغراض وملابس تحمل تصاميم ابتكرتها MAZIGHO. استكشف جميع المجموعات؛ يتم تأكيد التكلفة والمدة لوجهتك قبل أي طلب.", cta: "اكتشف المجموعات", globalTitle: "كتالوج ظاهر في كل مكان", globalText: "لا تختفي أي مجموعة بحسب البلد المختار.", customTitle: "ورشة مخصصة قريباً", customText: "ستُضاف إبداعات العملاء بعد مسار تحقق مخصص.", chooseEyebrow: "اختر نوع المنتج", collectionsTitle: "مجموعاتنا", collectionsText: "تضم كل مجموعة منتجات مميزة عن متجر الموردين المعتاد.", explore: "استكشف", discoverEyebrow: "اكتشف", preparingTitle: "مجموعات قيد الإعداد", destination: "الوجهة المختارة", deliveryPending: "التوصيل إلى {country} قيد التأكيد", firstTitle: "أول مجموعة MAZIGHO قيد الإعداد.", firstText: "الفئات مفتوحة للجميع بالفعل. لن تظهر أول تصاميم MAZIGHO إلا بعد التحقق من الصورة والحقوق والسعر والتوصيل.", categories: "عرض الفئات" } },
};

export function getCollectionsCopy(locale: StorefrontLocale): CollectionsCopy {
  return copy[locale] ?? copy.fr;
}
