import type { StorefrontLocale } from "@/contexts/LocaleContext";

type FavoritesCopy = { back: string; title: string; count: string; details: string; addCart: string; remove: string; added: string; empty: string; emptyText: string; discover: string };
const copy: Record<StorefrontLocale, FavoritesCopy> = {
  fr:{back:"Retour à l’accueil",title:"Mes favoris",count:"{count} produit(s) disponible(s) pour {country}",details:"Voir détails",addCart:"Ajouter au panier",remove:"Supprimer des favoris",added:"Ajouté au panier",empty:"Aucun favori disponible pour le moment",emptyText:"Aucun de vos favoris n’est encore confirmé pour la livraison vers {country}.",discover:"Découvrir les produits"},
  de:{back:"Zurück zur Startseite",title:"Meine Favoriten",count:"{count} Produkt(e) für {country} verfügbar",details:"Details ansehen",addCart:"In den Warenkorb",remove:"Aus Favoriten entfernen",added:"Zum Warenkorb hinzugefügt",empty:"Derzeit keine Favoriten verfügbar",emptyText:"Keiner Ihrer Favoriten ist noch für die Lieferung nach {country} bestätigt.",discover:"Produkte entdecken"},
  it:{back:"Torna alla home",title:"I miei preferiti",count:"{count} prodotto/i disponibile/i in {country}",details:"Vedi dettagli",addCart:"Aggiungi al carrello",remove:"Rimuovi dai preferiti",added:"Aggiunto al carrello",empty:"Nessun preferito disponibile al momento",emptyText:"Nessuno dei tuoi preferiti ha ancora una consegna confermata in {country}.",discover:"Scopri i prodotti"},
  en:{back:"Back to home",title:"My favorites",count:"{count} product(s) available for {country}",details:"View details",addCart:"Add to cart",remove:"Remove from favorites",added:"Added to cart",empty:"No favorites available yet",emptyText:"None of your favorites has confirmed delivery to {country} yet.",discover:"Discover products"},
  es:{back:"Volver al inicio",title:"Mis favoritos",count:"{count} producto(s) disponible(s) para {country}",details:"Ver detalles",addCart:"Añadir al carrito",remove:"Eliminar de favoritos",added:"Añadido al carrito",empty:"No hay favoritos disponibles por ahora",emptyText:"Ninguno de tus favoritos tiene aún entrega confirmada en {country}.",discover:"Descubrir productos"},
  nl:{back:"Terug naar home",title:"Mijn favorieten",count:"{count} product(en) beschikbaar voor {country}",details:"Details bekijken",addCart:"In winkelwagen",remove:"Uit favorieten verwijderen",added:"Toegevoegd aan winkelwagen",empty:"Nog geen favorieten beschikbaar",emptyText:"Geen van uw favorieten heeft nog bevestigde levering naar {country}.",discover:"Producten ontdekken"},
  ar:{back:"العودة إلى الرئيسية",title:"مفضلتي",count:"{count} منتج/منتجات متاحة للتوصيل إلى {country}",details:"عرض التفاصيل",addCart:"أضف إلى السلة",remove:"إزالة من المفضلة",added:"تمت الإضافة إلى السلة",empty:"لا توجد مفضلات متاحة حالياً",emptyText:"لا يوجد من مفضلاتك ما تم تأكيد توصيله إلى {country} بعد.",discover:"اكتشف المنتجات"},
};
export function favoritesT(locale: StorefrontLocale, key: keyof FavoritesCopy, values: Record<string,string|number> = {}) { return Object.entries(values).reduce((text,[name,value]) => text.replaceAll(`{${name}}`, String(value)), copy[locale]?.[key] ?? copy.fr[key]); }
