import type { StorefrontLocale } from "@/contexts/LocaleContext";

type MessageKey =
  | "topSelection" | "topDelivery" | "topQuote"
  | "home" | "shop" | "categories" | "creations" | "new" | "bestSellers" | "promotions" | "contact" | "faq" | "account" | "admin"
  | "deliveryCountry" | "language" | "deliverTo" | "displayLanguage"
  | "shopEyebrow" | "shopTitle" | "shopIntro" | "viewBestSellers" | "readyToDiscover" | "currentProducts"
  | "deliverableCount" | "offer" | "freeDelivery" | "delivery" | "days" | "noProducts"
  | "exploreUniverse" | "findYourStyle" | "viewNew" | "discover"
  | "editorialSelection" | "pricesInChf" | "switzerlandEurope"
  | "noTranslation" | "searchPlaceholder" | "searchProducts" | "searchCategories"
  | "viewAllResults" | "noResultsFor" | "clearSearch"
  | "previousBanner" | "nextBanner" | "showBanner"
  | "previousImage" | "nextImage" | "imageUnavailable"
  | "enlargeImage" | "enlarge" | "showImage" | "enlargedImage"
  | "openMenu" | "closeMenu";

type MessageDictionary = Record<MessageKey, string>;

const messages: Record<StorefrontLocale, MessageDictionary> = {
  fr: {
    topSelection: "Une sélection pensée pour le quotidien", topDelivery: "Livraison transparente selon la destination", topQuote: "Coût et délai confirmés avant achat",
    home: "Accueil", shop: "Boutique", categories: "Catégories", creations: "Créations", new: "Nouveautés", bestSellers: "Best-sellers", promotions: "Promos", contact: "Contact", faq: "FAQ", account: "Mon compte", admin: "Gestion MAZIGHO",
    deliveryCountry: "Pays de livraison", language: "Langue", deliverTo: "Livrer vers", displayLanguage: "Langue d’affichage",
    shopEyebrow: "La sélection MAZIGHO", shopTitle: "Notre Boutique", shopIntro: "Parcourez les produits dont la livraison est confirmée pour {country}.", viewBestSellers: "Voir les best-sellers", readyToDiscover: "Prêt à découvrir", currentProducts: "Nos produits du moment",
    deliverableCount: "{count} article(s) livrable(s) vers {country}", offer: "Offre", freeDelivery: "Livraison offerte", delivery: "Livraison", days: "jours", noProducts: "Aucun produit n’est encore confirmé pour la livraison vers {country}. Choisissez un autre pays ou revenez bientôt découvrir la sélection.",
    exploreUniverse: "Explorer par univers", findYourStyle: "Trouvez ce qui vous ressemble", viewNew: "Voir les nouveautés", discover: "Découvrir",
    editorialSelection: "Sélection éditoriale", pricesInChf: "Prix affichés en CHF", switzerlandEurope: "Livraison Suisse & Europe", noTranslation: "Cette fiche n’est pas encore disponible dans la langue choisie.", searchPlaceholder: "Rechercher un produit…", searchProducts: "Produits", searchCategories: "Catégories", viewAllResults: "Voir tous les résultats ({count})", noResultsFor: "Aucun résultat pour « {query} »", clearSearch: "Effacer la recherche", previousBanner: "Bannière précédente", nextBanner: "Bannière suivante", showBanner: "Afficher la bannière {index}", previousImage: "Image précédente", nextImage: "Image suivante", imageUnavailable: "Image indisponible", enlargeImage: "Agrandir l’image de {product}", enlarge: "Agrandir", showImage: "Afficher l’image {index}", enlargedImage: "Image agrandie : {product}", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu",
  },
  de: {
    topSelection: "Eine Auswahl für den Alltag", topDelivery: "Transparente Lieferung je nach Zielort", topQuote: "Kosten und Lieferzeit vor dem Kauf bestätigt",
    home: "Startseite", shop: "Shop", categories: "Kategorien", creations: "Kreationen", new: "Neuheiten", bestSellers: "Bestseller", promotions: "Angebote", contact: "Kontakt", faq: "FAQ", account: "Mein Konto", admin: "MAZIGHO Verwaltung",
    deliveryCountry: "Lieferland", language: "Sprache", deliverTo: "Liefern nach", displayLanguage: "Anzeigesprache",
    shopEyebrow: "Die MAZIGHO-Auswahl", shopTitle: "Unser Shop", shopIntro: "Entdecken Sie Produkte mit bestätigter Lieferung nach {country}.", viewBestSellers: "Bestseller ansehen", readyToDiscover: "Bereit zum Entdecken", currentProducts: "Unsere aktuellen Produkte",
    deliverableCount: "{count} lieferbare Artikel nach {country}", offer: "Angebot", freeDelivery: "Kostenlose Lieferung", delivery: "Lieferung", days: "Tage", noProducts: "Für {country} ist noch kein Produkt mit bestätigter Lieferung verfügbar. Wählen Sie ein anderes Land oder schauen Sie bald wieder vorbei.",
    exploreUniverse: "Nach Themen entdecken", findYourStyle: "Finden Sie, was zu Ihnen passt", viewNew: "Neuheiten ansehen", discover: "Entdecken",
    editorialSelection: "Redaktionelle Auswahl", pricesInChf: "Preise in CHF", switzerlandEurope: "Lieferung Schweiz & Europa", noTranslation: "Diese Produktseite ist in der gewählten Sprache noch nicht verfügbar.", searchPlaceholder: "Produkt suchen…", searchProducts: "Produkte", searchCategories: "Kategorien", viewAllResults: "Alle Ergebnisse anzeigen ({count})", noResultsFor: "Keine Ergebnisse für „{query}“", clearSearch: "Suche löschen", previousBanner: "Vorheriges Banner", nextBanner: "Nächstes Banner", showBanner: "Banner {index} anzeigen", previousImage: "Vorheriges Bild", nextImage: "Nächstes Bild", imageUnavailable: "Bild nicht verfügbar", enlargeImage: "Bild von {product} vergrößern", enlarge: "Vergrößern", showImage: "Bild {index} anzeigen", enlargedImage: "Vergrößertes Bild: {product}", openMenu: "Menü öffnen", closeMenu: "Menü schließen",
  },
  it: {
    topSelection: "Una selezione pensata per ogni giorno", topDelivery: "Consegna trasparente in base alla destinazione", topQuote: "Costi e tempi confermati prima dell’acquisto",
    home: "Home", shop: "Negozio", categories: "Categorie", creations: "Creazioni", new: "Novità", bestSellers: "Più venduti", promotions: "Promozioni", contact: "Contatto", faq: "FAQ", account: "Il mio account", admin: "Gestione MAZIGHO",
    deliveryCountry: "Paese di consegna", language: "Lingua", deliverTo: "Consegna in", displayLanguage: "Lingua di visualizzazione",
    shopEyebrow: "La selezione MAZIGHO", shopTitle: "Il nostro negozio", shopIntro: "Scopri i prodotti con consegna confermata per {country}.", viewBestSellers: "Vedi i più venduti", readyToDiscover: "Pronto a scoprire", currentProducts: "I prodotti del momento",
    deliverableCount: "{count} articoli consegnabili in {country}", offer: "Offerta", freeDelivery: "Consegna gratuita", delivery: "Consegna", days: "giorni", noProducts: "Nessun prodotto ha ancora una consegna confermata per {country}. Scegli un altro Paese o torna presto a scoprire la selezione.",
    exploreUniverse: "Esplora per universo", findYourStyle: "Trova ciò che ti rispecchia", viewNew: "Vedi le novità", discover: "Scopri",
    editorialSelection: "Selezione editoriale", pricesInChf: "Prezzi in CHF", switzerlandEurope: "Consegna Svizzera e Europa", noTranslation: "Questa pagina prodotto non è ancora disponibile nella lingua scelta.", searchPlaceholder: "Cerca un prodotto…", searchProducts: "Prodotti", searchCategories: "Categorie", viewAllResults: "Vedi tutti i risultati ({count})", noResultsFor: "Nessun risultato per “{query}”", clearSearch: "Cancella la ricerca", previousBanner: "Banner precedente", nextBanner: "Banner successivo", showBanner: "Mostra il banner {index}", previousImage: "Immagine precedente", nextImage: "Immagine successiva", imageUnavailable: "Immagine non disponibile", enlargeImage: "Ingrandisci l’immagine di {product}", enlarge: "Ingrandisci", showImage: "Mostra l’immagine {index}", enlargedImage: "Immagine ingrandita: {product}", openMenu: "Apri il menu", closeMenu: "Chiudi il menu",
  },
  en: {
    topSelection: "A selection made for everyday life", topDelivery: "Transparent delivery by destination", topQuote: "Cost and timing confirmed before purchase",
    home: "Home", shop: "Shop", categories: "Categories", creations: "Creations", new: "New arrivals", bestSellers: "Best sellers", promotions: "Offers", contact: "Contact", faq: "FAQ", account: "My account", admin: "MAZIGHO management",
    deliveryCountry: "Delivery country", language: "Language", deliverTo: "Deliver to", displayLanguage: "Display language",
    shopEyebrow: "The MAZIGHO selection", shopTitle: "Our Shop", shopIntro: "Browse products with delivery confirmed for {country}.", viewBestSellers: "View best sellers", readyToDiscover: "Ready to discover", currentProducts: "Our current products",
    deliverableCount: "{count} item(s) deliverable to {country}", offer: "Offer", freeDelivery: "Free delivery", delivery: "Delivery", days: "days", noProducts: "No product has confirmed delivery to {country} yet. Choose another country or come back soon to discover the selection.",
    exploreUniverse: "Explore by universe", findYourStyle: "Find what suits you", viewNew: "View new arrivals", discover: "Discover",
    editorialSelection: "Editorial selection", pricesInChf: "Prices shown in CHF", switzerlandEurope: "Delivery to Switzerland & Europe", noTranslation: "This product page is not yet available in the selected language.", searchPlaceholder: "Search for a product…", searchProducts: "Products", searchCategories: "Categories", viewAllResults: "View all results ({count})", noResultsFor: "No results for “{query}”", clearSearch: "Clear search", previousBanner: "Previous banner", nextBanner: "Next banner", showBanner: "Show banner {index}", previousImage: "Previous image", nextImage: "Next image", imageUnavailable: "Image unavailable", enlargeImage: "Enlarge image of {product}", enlarge: "Enlarge", showImage: "Show image {index}", enlargedImage: "Enlarged image: {product}", openMenu: "Open menu", closeMenu: "Close menu",
  },
  es: {
    topSelection: "Una selección pensada para el día a día", topDelivery: "Entrega transparente según el destino", topQuote: "Coste y plazo confirmados antes de comprar",
    home: "Inicio", shop: "Tienda", categories: "Categorías", creations: "Creaciones", new: "Novedades", bestSellers: "Más vendidos", promotions: "Ofertas", contact: "Contacto", faq: "Preguntas frecuentes", account: "Mi cuenta", admin: "Gestión MAZIGHO",
    deliveryCountry: "País de entrega", language: "Idioma", deliverTo: "Entregar en", displayLanguage: "Idioma de visualización",
    shopEyebrow: "La selección MAZIGHO", shopTitle: "Nuestra tienda", shopIntro: "Explora productos con entrega confirmada para {country}.", viewBestSellers: "Ver más vendidos", readyToDiscover: "Listo para descubrir", currentProducts: "Nuestros productos actuales",
    deliverableCount: "{count} artículo(s) disponibles para entrega en {country}", offer: "Oferta", freeDelivery: "Envío gratuito", delivery: "Entrega", days: "días", noProducts: "Aún no hay productos con entrega confirmada para {country}. Elige otro país o vuelve pronto para descubrir la selección.",
    exploreUniverse: "Explorar por universos", findYourStyle: "Encuentra lo que te representa", viewNew: "Ver novedades", discover: "Descubrir",
    editorialSelection: "Selección editorial", pricesInChf: "Precios mostrados en CHF", switzerlandEurope: "Entrega en Suiza y Europa", noTranslation: "Esta página de producto aún no está disponible en el idioma seleccionado.", searchPlaceholder: "Buscar un producto…", searchProducts: "Productos", searchCategories: "Categorías", viewAllResults: "Ver todos los resultados ({count})", noResultsFor: "No hay resultados para « {query} »", clearSearch: "Borrar búsqueda", previousBanner: "Banner anterior", nextBanner: "Banner siguiente", showBanner: "Mostrar el banner {index}", previousImage: "Imagen anterior", nextImage: "Imagen siguiente", imageUnavailable: "Imagen no disponible", enlargeImage: "Ampliar la imagen de {product}", enlarge: "Ampliar", showImage: "Mostrar la imagen {index}", enlargedImage: "Imagen ampliada: {product}", openMenu: "Abrir el menú", closeMenu: "Cerrar el menú",
  },
  nl: {
    topSelection: "Een selectie voor elke dag", topDelivery: "Transparante levering per bestemming", topQuote: "Kosten en levertijd bevestigd vóór aankoop",
    home: "Home", shop: "Winkel", categories: "Categorieën", creations: "Creaties", new: "Nieuw", bestSellers: "Bestsellers", promotions: "Aanbiedingen", contact: "Contact", faq: "Veelgestelde vragen", account: "Mijn account", admin: "MAZIGHO beheer",
    deliveryCountry: "Land van levering", language: "Taal", deliverTo: "Leveren naar", displayLanguage: "Weergavetaal",
    shopEyebrow: "De MAZIGHO-selectie", shopTitle: "Onze winkel", shopIntro: "Bekijk producten met bevestigde levering naar {country}.", viewBestSellers: "Bestsellers bekijken", readyToDiscover: "Klaar om te ontdekken", currentProducts: "Onze producten van het moment",
    deliverableCount: "{count} artikel(en) leverbaar naar {country}", offer: "Aanbieding", freeDelivery: "Gratis levering", delivery: "Levering", days: "dagen", noProducts: "Er is nog geen product met bevestigde levering naar {country}. Kies een ander land of kom binnenkort terug om de selectie te ontdekken.",
    exploreUniverse: "Ontdek per wereld", findYourStyle: "Vind wat bij je past", viewNew: "Nieuw bekijken", discover: "Ontdekken",
    editorialSelection: "Redactionele selectie", pricesInChf: "Prijzen in CHF", switzerlandEurope: "Levering in Zwitserland & Europa", noTranslation: "Deze productpagina is nog niet beschikbaar in de gekozen taal.", searchPlaceholder: "Een product zoeken…", searchProducts: "Producten", searchCategories: "Categorieën", viewAllResults: "Alle resultaten bekijken ({count})", noResultsFor: "Geen resultaten voor “{query}”", clearSearch: "Zoekopdracht wissen", previousBanner: "Vorige banner", nextBanner: "Volgende banner", showBanner: "Banner {index} weergeven", previousImage: "Vorige afbeelding", nextImage: "Volgende afbeelding", imageUnavailable: "Afbeelding niet beschikbaar", enlargeImage: "Afbeelding van {product} vergroten", enlarge: "Vergroten", showImage: "Afbeelding {index} weergeven", enlargedImage: "Vergrote afbeelding: {product}", openMenu: "Menu openen", closeMenu: "Menu sluiten",
  },
  ar: {
    topSelection: "تشكيلة مختارة للحياة اليومية", topDelivery: "توصيل واضح بحسب وجهة الشحن", topQuote: "تأكيد التكلفة والمدة قبل الشراء",
    home: "الرئيسية", shop: "المتجر", categories: "الفئات", creations: "الإبداعات", new: "وصل حديثاً", bestSellers: "الأكثر مبيعاً", promotions: "العروض", contact: "اتصل بنا", faq: "الأسئلة الشائعة", account: "حسابي", admin: "إدارة MAZIGHO",
    deliveryCountry: "بلد التوصيل", language: "اللغة", deliverTo: "التوصيل إلى", displayLanguage: "لغة العرض",
    shopEyebrow: "تشكيلة MAZIGHO", shopTitle: "متجرنا", shopIntro: "تصفح المنتجات التي تم تأكيد توصيلها إلى {country}.", viewBestSellers: "عرض الأكثر مبيعاً", readyToDiscover: "جاهز للاكتشاف", currentProducts: "منتجاتنا الحالية",
    deliverableCount: "{count} منتج/منتجات قابلة للتوصيل إلى {country}", offer: "عرض", freeDelivery: "توصيل مجاني", delivery: "التوصيل", days: "أيام", noProducts: "لا يوجد حتى الآن منتج تم تأكيد توصيله إلى {country}. اختر بلداً آخر أو عد قريباً لاكتشاف التشكيلة.",
    exploreUniverse: "استكشف حسب العالم", findYourStyle: "اعثر على ما يناسبك", viewNew: "عرض الجديد", discover: "اكتشف",
    editorialSelection: "اختيار تحريري", pricesInChf: "الأسعار معروضة بالفرنك السويسري", switzerlandEurope: "توصيل إلى سويسرا وأوروبا", noTranslation: "هذه الصفحة غير متاحة بعد باللغة المختارة.", searchPlaceholder: "ابحث عن منتج…", searchProducts: "المنتجات", searchCategories: "الفئات", viewAllResults: "عرض كل النتائج ({count})", noResultsFor: "لا توجد نتائج لـ «{query}»", clearSearch: "مسح البحث", previousBanner: "البانر السابق", nextBanner: "البانر التالي", showBanner: "عرض البانر {index}", previousImage: "الصورة السابقة", nextImage: "الصورة التالية", imageUnavailable: "الصورة غير متاحة", enlargeImage: "تكبير صورة {product}", enlarge: "تكبير", showImage: "عرض الصورة {index}", enlargedImage: "صورة مكبرة: {product}", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة",
  },
};

type CategoryMessageKey = "notFoundTitle" | "notFoundText" | "backShop" | "backCreations" | "creativeCollection" | "universe" | "dailySelection" | "creativeNotice" | "categoryNotice" | "deliveryIncluded" | "deliveryToConfirm" | "inStock" | "limitedStock" | "outOfStock" | "viewDetails" | "addToCart" | "addToWishlist" | "addedToCart" | "creativeEmpty" | "categoryEmpty" | "chooseCountryOrShop";

const categoryMessages: Record<StorefrontLocale, Record<CategoryMessageKey, string>> = {
  fr: { notFoundTitle: "Catégorie introuvable", notFoundText: "La catégorie que vous recherchez n’existe pas.", backShop: "Retour à la boutique", backCreations: "Retour aux créations", creativeCollection: "Collection créative MAZIGHO", universe: "Univers MAZIGHO", dailySelection: "Une sélection pensée pour votre quotidien.", creativeNotice: "Cette collection présente des designs MAZIGHO et reste visible partout. Le prix et le délai de livraison sont confirmés pour {country} avant l’ajout au panier.", categoryNotice: "Découvrez notre sélection {category}, dont la livraison est confirmée vers {country}.", deliveryIncluded: "Livraison incluse", deliveryToConfirm: "Livraison à confirmer pour {country}", inStock: "✓ En stock", limitedStock: "⚠ Stock limité", outOfStock: "✗ Rupture de stock", viewDetails: "Voir les détails", addToCart: "Ajouter au panier", addToWishlist: "Ajouter aux favoris", addedToCart: "✓ Ajouté au panier", creativeEmpty: "Cette collection de designs MAZIGHO est ouverte à tous, mais ses premiers produits sont encore en préparation.", categoryEmpty: "Aucun produit de cette catégorie n’est encore confirmé pour la livraison vers {country}.", chooseCountryOrShop: "Choisir un autre pays ou voir la boutique" },
  de: { notFoundTitle: "Kategorie nicht gefunden", notFoundText: "Die gesuchte Kategorie existiert nicht.", backShop: "Zurück zum Shop", backCreations: "Zurück zu den Kreationen", creativeCollection: "Kreative MAZIGHO-Kollektion", universe: "MAZIGHO-Welt", dailySelection: "Eine Auswahl für Ihren Alltag.", creativeNotice: "Diese Kollektion zeigt MAZIGHO-Designs und bleibt weltweit sichtbar. Preis und Lieferzeit werden für {country} vor dem Hinzufügen zum Warenkorb bestätigt.", categoryNotice: "Entdecken Sie unsere Auswahl {category} mit bestätigter Lieferung nach {country}.", deliveryIncluded: "Lieferung inbegriffen", deliveryToConfirm: "Lieferung nach {country} noch zu bestätigen", inStock: "✓ Auf Lager", limitedStock: "⚠ Begrenzter Bestand", outOfStock: "✗ Nicht auf Lager", viewDetails: "Details ansehen", addToCart: "In den Warenkorb", addToWishlist: "Zu Favoriten hinzufügen", addedToCart: "✓ Zum Warenkorb hinzugefügt", creativeEmpty: "Diese MAZIGHO-Designkollektion ist für alle sichtbar, ihre ersten Produkte werden jedoch noch vorbereitet.", categoryEmpty: "Für diese Kategorie ist noch kein Produkt mit bestätigter Lieferung nach {country} verfügbar.", chooseCountryOrShop: "Anderes Land wählen oder Shop ansehen" },
  it: { notFoundTitle: "Categoria non trovata", notFoundText: "La categoria cercata non esiste.", backShop: "Torna al negozio", backCreations: "Torna alle creazioni", creativeCollection: "Collezione creativa MAZIGHO", universe: "Universo MAZIGHO", dailySelection: "Una selezione pensata per la tua quotidianità.", creativeNotice: "Questa collezione presenta design MAZIGHO e resta visibile ovunque. Prezzo e tempi di consegna vengono confermati per {country} prima dell’aggiunta al carrello.", categoryNotice: "Scopri la nostra selezione {category}, con consegna confermata in {country}.", deliveryIncluded: "Consegna inclusa", deliveryToConfirm: "Consegna da confermare per {country}", inStock: "✓ Disponibile", limitedStock: "⚠ Scorte limitate", outOfStock: "✗ Esaurito", viewDetails: "Vedi dettagli", addToCart: "Aggiungi al carrello", addToWishlist: "Aggiungi ai preferiti", addedToCart: "✓ Aggiunto al carrello", creativeEmpty: "Questa collezione di design MAZIGHO è visibile a tutti, ma i primi prodotti sono ancora in preparazione.", categoryEmpty: "Nessun prodotto di questa categoria ha ancora una consegna confermata in {country}.", chooseCountryOrShop: "Scegli un altro Paese o visita il negozio" },
  en: { notFoundTitle: "Category not found", notFoundText: "The category you are looking for does not exist.", backShop: "Back to shop", backCreations: "Back to creations", creativeCollection: "MAZIGHO creative collection", universe: "MAZIGHO universe", dailySelection: "A selection designed for your everyday life.", creativeNotice: "This collection presents MAZIGHO designs and remains visible worldwide. Price and delivery time are confirmed for {country} before adding to the cart.", categoryNotice: "Discover our {category} selection, with delivery confirmed to {country}.", deliveryIncluded: "Delivery included", deliveryToConfirm: "Delivery to {country} to be confirmed", inStock: "✓ In stock", limitedStock: "⚠ Limited stock", outOfStock: "✗ Out of stock", viewDetails: "View details", addToCart: "Add to cart", addToWishlist: "Add to favourites", addedToCart: "✓ Added to cart", creativeEmpty: "This MAZIGHO design collection is visible to everyone, but its first products are still being prepared.", categoryEmpty: "No product in this category has confirmed delivery to {country} yet.", chooseCountryOrShop: "Choose another country or view the shop" },
  es: { notFoundTitle: "Categoría no encontrada", notFoundText: "La categoría que buscas no existe.", backShop: "Volver a la tienda", backCreations: "Volver a las creaciones", creativeCollection: "Colección creativa MAZIGHO", universe: "Universo MAZIGHO", dailySelection: "Una selección pensada para tu día a día.", creativeNotice: "Esta colección presenta diseños MAZIGHO y sigue visible en todo el mundo. El precio y el plazo de entrega se confirman para {country} antes de añadir al carrito.", categoryNotice: "Descubre nuestra selección {category}, con entrega confirmada en {country}.", deliveryIncluded: "Envío incluido", deliveryToConfirm: "Entrega por confirmar para {country}", inStock: "✓ En stock", limitedStock: "⚠ Stock limitado", outOfStock: "✗ Agotado", viewDetails: "Ver detalles", addToCart: "Añadir al carrito", addToWishlist: "Añadir a favoritos", addedToCart: "✓ Añadido al carrito", creativeEmpty: "Esta colección de diseños MAZIGHO es visible para todos, pero sus primeros productos aún se están preparando.", categoryEmpty: "Aún no hay productos de esta categoría con entrega confirmada en {country}.", chooseCountryOrShop: "Elige otro país o visita la tienda" },
  nl: { notFoundTitle: "Categorie niet gevonden", notFoundText: "De gezochte categorie bestaat niet.", backShop: "Terug naar de winkel", backCreations: "Terug naar de creaties", creativeCollection: "Creatieve MAZIGHO-collectie", universe: "MAZIGHO-wereld", dailySelection: "Een selectie voor je dagelijks leven.", creativeNotice: "Deze collectie toont MAZIGHO-ontwerpen en blijft wereldwijd zichtbaar. Prijs en levertijd worden voor {country} bevestigd voordat je het product aan de winkelwagen toevoegt.", categoryNotice: "Ontdek onze selectie {category}, met bevestigde levering naar {country}.", deliveryIncluded: "Levering inbegrepen", deliveryToConfirm: "Levering naar {country} moet nog worden bevestigd", inStock: "✓ Op voorraad", limitedStock: "⚠ Beperkte voorraad", outOfStock: "✗ Niet op voorraad", viewDetails: "Details bekijken", addToCart: "In winkelwagen", addToWishlist: "Toevoegen aan favorieten", addedToCart: "✓ Toegevoegd aan winkelwagen", creativeEmpty: "Deze MAZIGHO-designcollectie is voor iedereen zichtbaar, maar de eerste producten worden nog voorbereid.", categoryEmpty: "Er is nog geen product in deze categorie met bevestigde levering naar {country}.", chooseCountryOrShop: "Kies een ander land of bekijk de winkel" },
  ar: { notFoundTitle: "الفئة غير موجودة", notFoundText: "الفئة التي تبحث عنها غير موجودة.", backShop: "العودة إلى المتجر", backCreations: "العودة إلى الإبداعات", creativeCollection: "مجموعة MAZIGHO الإبداعية", universe: "عالم MAZIGHO", dailySelection: "تشكيلة مصممة لحياتك اليومية.", creativeNotice: "تعرض هذه المجموعة تصاميم MAZIGHO وتظل مرئية في جميع أنحاء العالم. يتم تأكيد السعر ومدة التوصيل إلى {country} قبل الإضافة إلى السلة.", categoryNotice: "اكتشف تشكيلتنا {category} مع توصيل مؤكد إلى {country}.", deliveryIncluded: "التوصيل مشمول", deliveryToConfirm: "التوصيل إلى {country} يحتاج إلى تأكيد", inStock: "✓ متوفر", limitedStock: "⚠ مخزون محدود", outOfStock: "✗ غير متوفر", viewDetails: "عرض التفاصيل", addToCart: "أضف إلى السلة", addToWishlist: "أضف إلى المفضلة", addedToCart: "✓ تمت الإضافة إلى السلة", creativeEmpty: "مجموعة تصاميم MAZIGHO هذه مرئية للجميع، لكن منتجاتها الأولى لا تزال قيد التحضير.", categoryEmpty: "لا يوجد حتى الآن منتج في هذه الفئة تم تأكيد توصيله إلى {country}.", chooseCountryOrShop: "اختر بلداً آخر أو شاهد المتجر" },
};

export function categoryT(locale: StorefrontLocale, key: CategoryMessageKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, String(value)), categoryMessages[locale]?.[key] ?? categoryMessages.fr[key]);
}

type CommerceMessageKey = "productNotFoundTitle" | "productNotFoundText" | "backToShop" | "creations" | "shop" | "reviews" | "save" | "availableTo" | "deliveryIncluded" | "shippingPerItem" | "deliveryEstimate" | "quoteVerified" | "deliveryUnconfirmed" | "deliveryBlocked" | "inStock" | "outOfStock" | "quantity" | "added" | "addToCart" | "paymentSoon" | "noPaymentNow" | "orderReview" | "rechecked" | "destinationUnconfirmed" | "chooseOtherCountry";

const commerceMessages: Record<StorefrontLocale, Record<CommerceMessageKey, string>> = {
  fr: { productNotFoundTitle: "Produit non trouvé", productNotFoundText: "Le produit que vous recherchez n’existe pas.", backToShop: "Retour à la boutique", creations: "Créations", shop: "Boutique", reviews: "avis", save: "Économisez {percent}%", availableTo: "Livrable vers {country}", deliveryIncluded: "Livraison incluse dans le prix", shippingPerItem: "{amount} par article", deliveryEstimate: "délai estimé {min}{range} jours", quoteVerified: "Devis fournisseur vérifié pour cette destination.", deliveryUnconfirmed: "Livraison non confirmée vers {country}", deliveryBlocked: "Ce produit ne peut pas être ajouté au panier pour le pays actuellement choisi. Sélectionnez une autre destination pour vérifier sa disponibilité.", inStock: "✓ En stock ({count} disponibles)", outOfStock: "✗ Rupture de stock", quantity: "Quantité", added: "Ajouté !", addToCart: "Ajouter au panier", paymentSoon: "Paiement à venir", noPaymentNow: "Aucune donnée de paiement demandée maintenant", orderReview: "Commande encadrée", rechecked: "Informations revérifiées avant activation", destinationUnconfirmed: "Destination non confirmée", chooseOtherCountry: "Choisissez un autre pays" },
  de: { productNotFoundTitle: "Produkt nicht gefunden", productNotFoundText: "Das gesuchte Produkt existiert nicht.", backToShop: "Zurück zum Shop", creations: "Kreationen", shop: "Shop", reviews: "Bewertungen", save: "Sie sparen {percent}%", availableTo: "Lieferbar nach {country}", deliveryIncluded: "Lieferung im Preis inbegriffen", shippingPerItem: "{amount} pro Artikel", deliveryEstimate: "voraussichtliche Lieferzeit {min}{range} Tage", quoteVerified: "Lieferantenangebot für dieses Ziel geprüft.", deliveryUnconfirmed: "Lieferung nach {country} nicht bestätigt", deliveryBlocked: "Dieses Produkt kann für das aktuell gewählte Land nicht in den Warenkorb gelegt werden. Wählen Sie ein anderes Land, um die Verfügbarkeit zu prüfen.", inStock: "✓ Auf Lager ({count} verfügbar)", outOfStock: "✗ Nicht auf Lager", quantity: "Menge", added: "Hinzugefügt!", addToCart: "In den Warenkorb", paymentSoon: "Zahlung folgt", noPaymentNow: "Derzeit werden keine Zahlungsdaten abgefragt", orderReview: "Bestellung kontrolliert", rechecked: "Informationen werden vor der Aktivierung erneut geprüft", destinationUnconfirmed: "Ziel nicht bestätigt", chooseOtherCountry: "Wählen Sie ein anderes Land" },
  it: { productNotFoundTitle: "Prodotto non trovato", productNotFoundText: "Il prodotto cercato non esiste.", backToShop: "Torna al negozio", creations: "Creazioni", shop: "Negozio", reviews: "recensioni", save: "Risparmi {percent}%", availableTo: "Consegna disponibile in {country}", deliveryIncluded: "Consegna inclusa nel prezzo", shippingPerItem: "{amount} per articolo", deliveryEstimate: "tempo stimato {min}{range} giorni", quoteVerified: "Preventivo del fornitore verificato per questa destinazione.", deliveryUnconfirmed: "Consegna non confermata in {country}", deliveryBlocked: "Questo prodotto non può essere aggiunto al carrello per il Paese selezionato. Scegli un’altra destinazione per verificarne la disponibilità.", inStock: "✓ Disponibile ({count} disponibili)", outOfStock: "✗ Esaurito", quantity: "Quantità", added: "Aggiunto!", addToCart: "Aggiungi al carrello", paymentSoon: "Pagamento in arrivo", noPaymentNow: "Al momento non vengono richiesti dati di pagamento", orderReview: "Ordine controllato", rechecked: "Informazioni ricontrollate prima dell’attivazione", destinationUnconfirmed: "Destinazione non confermata", chooseOtherCountry: "Scegli un altro Paese" },
  en: { productNotFoundTitle: "Product not found", productNotFoundText: "The product you are looking for does not exist.", backToShop: "Back to shop", creations: "Creations", shop: "Shop", reviews: "reviews", save: "Save {percent}%", availableTo: "Deliverable to {country}", deliveryIncluded: "Delivery included in the price", shippingPerItem: "{amount} per item", deliveryEstimate: "estimated delivery {min}{range} days", quoteVerified: "Supplier quote verified for this destination.", deliveryUnconfirmed: "Delivery to {country} not confirmed", deliveryBlocked: "This product cannot be added to the cart for the currently selected country. Choose another destination to check availability.", inStock: "✓ In stock ({count} available)", outOfStock: "✗ Out of stock", quantity: "Quantity", added: "Added!", addToCart: "Add to cart", paymentSoon: "Payment coming soon", noPaymentNow: "No payment information is requested at this time", orderReview: "Order controlled", rechecked: "Information checked again before activation", destinationUnconfirmed: "Destination not confirmed", chooseOtherCountry: "Choose another country" },
  es: { productNotFoundTitle: "Producto no encontrado", productNotFoundText: "El producto que buscas no existe.", backToShop: "Volver a la tienda", creations: "Creaciones", shop: "Tienda", reviews: "reseñas", save: "Ahorras {percent}%", availableTo: "Disponible para entrega en {country}", deliveryIncluded: "Envío incluido en el precio", shippingPerItem: "{amount} por artículo", deliveryEstimate: "plazo estimado {min}{range} días", quoteVerified: "Presupuesto del proveedor verificado para este destino.", deliveryUnconfirmed: "Entrega no confirmada en {country}", deliveryBlocked: "Este producto no puede añadirse al carrito para el país seleccionado. Elige otro destino para comprobar la disponibilidad.", inStock: "✓ En stock ({count} disponibles)", outOfStock: "✗ Agotado", quantity: "Cantidad", added: "¡Añadido!", addToCart: "Añadir al carrito", paymentSoon: "Pago próximamente", noPaymentNow: "No se solicitan datos de pago por ahora", orderReview: "Pedido controlado", rechecked: "Información revisada antes de la activación", destinationUnconfirmed: "Destino no confirmado", chooseOtherCountry: "Elige otro país" },
  nl: { productNotFoundTitle: "Product niet gevonden", productNotFoundText: "Het product dat je zoekt bestaat niet.", backToShop: "Terug naar de winkel", creations: "Creaties", shop: "Winkel", reviews: "beoordelingen", save: "Je bespaart {percent}%", availableTo: "Leverbaar naar {country}", deliveryIncluded: "Levering inbegrepen in de prijs", shippingPerItem: "{amount} per artikel", deliveryEstimate: "geschatte levertijd {min}{range} dagen", quoteVerified: "Leveranciersofferte voor deze bestemming geverifieerd.", deliveryUnconfirmed: "Levering naar {country} niet bevestigd", deliveryBlocked: "Dit product kan niet aan de winkelwagen worden toegevoegd voor het geselecteerde land. Kies een andere bestemming om de beschikbaarheid te controleren.", inStock: "✓ Op voorraad ({count} beschikbaar)", outOfStock: "✗ Niet op voorraad", quantity: "Aantal", added: "Toegevoegd!", addToCart: "In winkelwagen", paymentSoon: "Betaling binnenkort", noPaymentNow: "Er worden nu geen betalingsgegevens gevraagd", orderReview: "Bestelling gecontroleerd", rechecked: "Informatie wordt opnieuw gecontroleerd vóór activering", destinationUnconfirmed: "Bestemming niet bevestigd", chooseOtherCountry: "Kies een ander land" },
  ar: { productNotFoundTitle: "المنتج غير موجود", productNotFoundText: "المنتج الذي تبحث عنه غير موجود.", backToShop: "العودة إلى المتجر", creations: "الإبداعات", shop: "المتجر", reviews: "مراجعات", save: "وفّر {percent}%", availableTo: "متاح للتوصيل إلى {country}", deliveryIncluded: "التوصيل مشمول في السعر", shippingPerItem: "{amount} لكل قطعة", deliveryEstimate: "المدة التقديرية {min}{range} أيام", quoteVerified: "تم التحقق من عرض المورد لهذه الوجهة.", deliveryUnconfirmed: "التوصيل إلى {country} غير مؤكد", deliveryBlocked: "لا يمكن إضافة هذا المنتج إلى السلة للبلد المحدد حالياً. اختر وجهة أخرى للتحقق من التوفر.", inStock: "✓ متوفر ({count} قطعة)", outOfStock: "✗ غير متوفر", quantity: "الكمية", added: "تمت الإضافة!", addToCart: "أضف إلى السلة", paymentSoon: "الدفع قريباً", noPaymentNow: "لا يتم طلب أي بيانات دفع حالياً", orderReview: "طلب مراقَب", rechecked: "تُراجع المعلومات مجدداً قبل التفعيل", destinationUnconfirmed: "الوجهة غير مؤكدة", chooseOtherCountry: "اختر بلداً آخر" },
};

export function commerceT(locale: StorefrontLocale, key: CommerceMessageKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, String(value)), commerceMessages[locale]?.[key] ?? commerceMessages.fr[key]);
}

export function t(locale: StorefrontLocale, key: MessageKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce(
    (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
    messages[locale]?.[key] ?? messages.fr[key],
  );
}
