import type { StorefrontLocale } from "@/contexts/LocaleContext";

const reviewCopies = {
  fr: { rating: "Note", bad: "Mauvais", average: "Moyen", good: "Bon", veryGood: "Très bon", excellent: "Excellent", name: "Votre nom", enterName: "Entrez votre nom", email: "Votre email", review: "Votre avis", shareExperience: "Partagez votre expérience avec ce produit…", submitting: "Envoi en cours…", publish: "Publier mon avis", moderation: "Votre avis sera publié après modération. Merci de votre contribution !", fillAll: "Veuillez remplir tous les champs", validEmail: "Veuillez entrer une adresse email valide", characters: "caractères" },
  de: { rating: "Bewertung", bad: "Schlecht", average: "Mittel", good: "Gut", veryGood: "Sehr gut", excellent: "Ausgezeichnet", name: "Ihr Name", enterName: "Geben Sie Ihren Namen ein", email: "Ihre E-Mail-Adresse", review: "Ihre Bewertung", shareExperience: "Teilen Sie Ihre Erfahrung mit diesem Produkt…", submitting: "Wird gesendet…", publish: "Bewertung veröffentlichen", moderation: "Ihre Bewertung wird nach der Moderation veröffentlicht. Vielen Dank für Ihren Beitrag!", fillAll: "Bitte füllen Sie alle Felder aus", validEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein", characters: "Zeichen" },
  it: { rating: "Valutazione", bad: "Scarso", average: "Medio", good: "Buono", veryGood: "Molto buono", excellent: "Eccellente", name: "Il tuo nome", enterName: "Inserisci il tuo nome", email: "La tua email", review: "La tua recensione", shareExperience: "Condividi la tua esperienza con questo prodotto…", submitting: "Invio in corso…", publish: "Pubblica la recensione", moderation: "La tua recensione sarà pubblicata dopo la moderazione. Grazie per il tuo contributo!", fillAll: "Compila tutti i campi", validEmail: "Inserisci un indirizzo email valido", characters: "caratteri" },
  en: { rating: "Rating", bad: "Poor", average: "Average", good: "Good", veryGood: "Very good", excellent: "Excellent", name: "Your name", enterName: "Enter your name", email: "Your email", review: "Your review", shareExperience: "Share your experience with this product…", submitting: "Submitting…", publish: "Publish my review", moderation: "Your review will be published after moderation. Thank you for your contribution!", fillAll: "Please fill in all fields", validEmail: "Please enter a valid email address", characters: "characters" },
  es: { rating: "Valoración", bad: "Malo", average: "Regular", good: "Bueno", veryGood: "Muy bueno", excellent: "Excelente", name: "Tu nombre", enterName: "Introduce tu nombre", email: "Tu correo electrónico", review: "Tu opinión", shareExperience: "Comparte tu experiencia con este producto…", submitting: "Enviando…", publish: "Publicar mi opinión", moderation: "Tu opinión se publicará después de la moderación. ¡Gracias por tu contribución!", fillAll: "Completa todos los campos", validEmail: "Introduce una dirección de correo válida", characters: "caracteres" },
  nl: { rating: "Beoordeling", bad: "Slecht", average: "Gemiddeld", good: "Goed", veryGood: "Zeer goed", excellent: "Uitstekend", name: "Je naam", enterName: "Vul je naam in", email: "Je e-mailadres", review: "Je beoordeling", shareExperience: "Deel je ervaring met dit product…", submitting: "Wordt verzonden…", publish: "Mijn beoordeling publiceren", moderation: "Je beoordeling wordt na moderatie gepubliceerd. Bedankt voor je bijdrage!", fillAll: "Vul alle velden in", validEmail: "Vul een geldig e-mailadres in", characters: "tekens" },
  ar: { rating: "التقييم", bad: "ضعيف", average: "متوسط", good: "جيد", veryGood: "جيد جداً", excellent: "ممتاز", name: "اسمك", enterName: "أدخل اسمك", email: "بريدك الإلكتروني", review: "رأيك", shareExperience: "شارك تجربتك مع هذا المنتج…", submitting: "جارٍ الإرسال…", publish: "نشر رأيي", moderation: "سيُنشر رأيك بعد المراجعة. شكراً لمساهمتك!", fillAll: "يرجى ملء جميع الحقول", validEmail: "يرجى إدخال عنوان بريد إلكتروني صالح", characters: "حرفاً" },
} as const satisfies Record<StorefrontLocale, Record<string, string>>;

export function getReviewCopy(locale: StorefrontLocale) {
  return reviewCopies[locale];
}
