import { Link } from "wouter";
import { ArrowRight, ArrowUpRight, Check, Sparkles, Store, Loader2 } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { trpc } from "@/lib/trpc";
import { formatPrice } from "@/lib/currency";
import { getDeliveryProfileForCountry, useDeliveryCountry } from "@/contexts/DeliveryCountryContext";
import { useLocale } from "@/contexts/LocaleContext";
import { t } from "@/lib/i18n";
import { getLocalizedCategoryPresentation } from "@/lib/categoryPresentation";

const categoryAccents = ["bg-orange-50 text-orange-700", "bg-sky-50 text-sky-700", "bg-rose-50 text-rose-700", "bg-emerald-50 text-emerald-700", "bg-violet-50 text-violet-700", "bg-amber-50 text-amber-700"];

export default function Shop() {
  const { locale } = useLocale();
  const categoriesQuery = trpc.categories.getAll.useQuery(locale);
  const productsQuery = trpc.products.getAll.useQuery(locale);
  const categories = (categoriesQuery.data || []).map(category => getLocalizedCategoryPresentation(locale, category));
  const standardCategories = categories.filter(category => category.catalogSection !== "creations");
  const standardCategoryIds = new Set(standardCategories.map(category => category.id));
  const { countryCode, countryLabel } = useDeliveryCountry();
  const products = (productsQuery.data || []).filter(product => standardCategoryIds.has(product.categoryId) && product.stock > 0 && getDeliveryProfileForCountry(product.deliveryProfiles, countryCode));

  return <div className="min-h-screen bg-[#fbf7f2] text-slate-900"><Header /><main>
    <section className="border-b border-[#eadfd2] bg-white px-4 py-10 md:py-14"><div className="container"><p className="mb-3 text-xs font-bold uppercase tracking-[0.28em] text-orange-600">{t(locale, "shopEyebrow")}</p><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><h1 className="text-4xl font-semibold tracking-tight text-slate-950 md:text-5xl">{t(locale, "shopTitle")}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-slate-600">{t(locale, "shopIntro", { country: countryLabel })}</p></div><Link href="/best-sellers" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-800 hover:text-orange-600">{t(locale, "viewBestSellers")} <ArrowUpRight className="h-4 w-4" /></Link></div></div></section>
    <section className="bg-white py-10 md:py-14"><div className="container"><div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.25em] text-orange-600">{t(locale, "readyToDiscover")}</p><h2 className="text-2xl font-semibold tracking-tight text-slate-950 md:text-3xl">{t(locale, "currentProducts")}</h2></div><span className="text-sm text-slate-500">{t(locale, "deliverableCount", { count: products.length, country: countryLabel })}</span></div>{productsQuery.isLoading ? <div className="flex justify-center py-16"><Loader2 className="h-9 w-9 animate-spin text-orange-500" /></div> : products.length > 0 ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 8).map((product) => { const imageUrl = product.images?.[0]?.imageUrl; const hasDiscount = Boolean(product.originalPrice && product.originalPrice > product.price); return <Link key={product.id} href={`/produit/${product.slug}`}><article className="group overflow-hidden border border-[#eadfd2] bg-[#fbf7f2] transition-all duration-200 hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden bg-[#f2eee9]">{imageUrl ? <img src={imageUrl} alt={product.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-5xl text-slate-300">✦</div>}{hasDiscount && <span className="absolute left-3 top-3 rounded-full bg-orange-500 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{t(locale, "offer")}</span>}</div><div className="p-5"><h3 className="line-clamp-2 min-h-[3rem] text-sm font-semibold leading-6 text-slate-900 group-hover:text-orange-600">{product.name}</h3><div className="mt-3 flex items-baseline gap-2"><span className="font-bold text-orange-600">{formatPrice(product.price, locale)}</span>{hasDiscount && <span className="text-xs text-slate-400 line-through">{formatPrice(product.originalPrice!, locale)}</span>}</div>{(() => { const profile = getDeliveryProfileForCountry(product.deliveryProfiles, countryCode); return profile ? <div className="mt-3 border-t border-[#eadfd2] pt-2 text-[11px] leading-5 text-slate-600"><p className="font-semibold text-emerald-700"><Check className="mr-1 inline h-3.5 w-3.5" />Livraison vérifiée pour {countryLabel}</p><p>{profile.customerShippingCost === 0 ? "Livraison incluse" : `${formatPrice(profile.customerShippingCost, locale)} par article`}{profile.minDeliveryDays ? ` · ${profile.minDeliveryDays}${profile.maxDeliveryDays && profile.maxDeliveryDays !== profile.minDeliveryDays ? `–${profile.maxDeliveryDays}` : ""} ${t(locale, "days")}` : ""}</p></div> : null; })()}</div></article></Link>; })}</div> : <div className="border border-dashed border-[#d9cbbc] bg-[#fbf7f2] px-6 py-12 text-center text-sm text-slate-500">{t(locale, "noProducts", { country: countryLabel })}</div>}</div></section>
    <section className="border-y border-[#eadfd2] bg-[#f1ebe4] py-12 md:py-16"><div className="container"><div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.25em] text-orange-600">{t(locale, "exploreUniverse")}</p><h2 className="text-2xl font-semibold tracking-tight text-slate-950 md:text-3xl">{t(locale, "findYourStyle")}</h2></div><Link href="/nouveautes" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-800 hover:text-orange-600">{t(locale, "viewNew")} <ArrowUpRight className="h-4 w-4" /></Link></div>{categoriesQuery.isLoading ? <div className="flex justify-center py-10"><Loader2 className="h-8 w-8 animate-spin text-orange-500" /></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{standardCategories.map((category, index) => <Link key={category.id} href={`/categorie/${category.slug}`}><article className="group flex min-h-[132px] items-center gap-4 border border-[#eadfd2] bg-white p-5 transition-all hover:-translate-y-1 hover:border-orange-300 hover:shadow-lg"><div className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl ${categoryAccents[index % categoryAccents.length]}`}><span className="text-2xl" aria-hidden="true">{category.icon || "✦"}</span></div><div className="min-w-0 flex-1"><h3 className="text-base font-semibold text-slate-900 group-hover:text-orange-600">{category.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{category.description}</p><span className="mt-2 inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-orange-600">{t(locale, "discover")} <ArrowRight className="h-3 w-3" /></span></div></article></Link>)}</div>}</div></section>
    <section className="container py-10 md:py-14"><div className="relative min-h-[210px] overflow-hidden rounded-[1.75rem] bg-slate-950"><img src="/assets/shop-editorial-hero.jpg" alt="Ambiance éditoriale MAZIGHO" className="absolute inset-0 h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950/85 via-slate-950/40 to-transparent" /><div className="relative flex min-h-[210px] items-center px-7 py-8 text-white md:px-12"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-orange-300">L'expérience MAZIGHO</p><h2 className="mt-3 max-w-lg text-2xl font-semibold md:text-3xl">Des trouvailles utiles, sélectionnées avec soin.</h2></div></div></div></section>
    <section className="border-y border-[#eadfd2] bg-white"><div className="container grid gap-0 md:grid-cols-3"><div className="flex items-center gap-3 border-b border-[#eadfd2] py-5 md:border-b-0 md:border-r md:pr-8"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-orange-100 text-orange-600"><Sparkles className="h-4 w-4" /></div><p className="text-sm font-semibold">{t(locale, "editorialSelection")}</p></div><div className="flex items-center gap-3 border-b border-[#eadfd2] py-5 md:border-b-0 md:border-r md:px-8"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-sky-100 text-sky-700"><Check className="h-4 w-4" /></div><p className="text-sm font-semibold">{t(locale, "pricesInChf")}</p></div><div className="flex items-center gap-3 py-5 md:pl-8"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Store className="h-4 w-4" /></div><p className="text-sm font-semibold">{t(locale, "switzerlandEurope")}</p></div></div></section>
  </main><Footer /></div>;
}
