import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUp, CircleAlert, ImagePlus, LockKeyhole, PackagePlus, PencilLine, Plus, Save, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";

type Category = { id: number; name: string; slug: string; description: string | null; displayOrder: number };
type VariantOption = { name: string; values: string[] };
type Product = { id: number; categoryId: number; name: string; slug: string; description: string | null; longDescription: string | null; price: number; stock: number; featured: boolean; status: "active" | "draft" | "archived"; images: string[]; options: string | null };
type ProductInput = { categoryId: number; name: string; description: string; longDescription: string; priceCents: number; stock: number; featured: boolean; images: string[]; options: VariantOption[] };

export default function AdminStudioOwnerExistingCatalogueEditor() {
  const [, setLocation] = useLocation();
  const [, params] = useRoute("/admin/studio/catalogue-existant/:storeId");
  const storeId = Number(params?.storeId);
  const validStoreId = Number.isInteger(storeId) && storeId > 0;
  const utils = trpc.useUtils();
  const query = trpc.admin.studio.getOwnerExistingCatalogue.useQuery({ storeId: validStoreId ? storeId : 0 }, { enabled: validStoreId, retry: false, refetchOnWindowFocus: false });
  const [addOpen, setAddOpen] = useState(false);
  const saveCategory = trpc.admin.studio.saveOwnerExistingCatalogueCategory.useMutation({ onSuccess: () => utils.admin.studio.getOwnerExistingCatalogue.invalidate({ storeId }) });
  const saveProduct = trpc.admin.studio.saveOwnerExistingCatalogueProduct.useMutation({ onSuccess: () => utils.admin.studio.getOwnerExistingCatalogue.invalidate({ storeId }) });
  const createProduct = trpc.admin.studio.createOwnerExistingCatalogueProduct.useMutation({ onSuccess: () => { setAddOpen(false); utils.admin.studio.getOwnerExistingCatalogue.invalidate({ storeId }); } });
  const uploadProductImage = trpc.admin.studio.uploadOwnerExistingCatalogueProductImage.useMutation();
  const uploadImage = async (productId: number, file: File) => {
    if (file.size > 5 * 1024 * 1024) throw new Error("L’image dépasse 5 Mo.");
    const dataUrl = await readFileAsDataUrl(file);
    const result = await uploadProductImage.mutateAsync({ storeId, productId, dataUrl, fileName: file.name });
    return result.url;
  };

  if (!validStoreId) return <DashboardLayout><main className="mx-auto w-full max-w-5xl px-4 py-8 md:px-8"><Unavailable /></main></DashboardLayout>;
  if (query.isLoading) return <DashboardLayout><main className="mx-auto w-full max-w-6xl px-4 py-8 md:px-8"><div className="h-[680px] animate-pulse rounded-3xl bg-slate-100" /></main></DashboardLayout>;
  if (query.isError || !query.data) return <DashboardLayout><main className="mx-auto w-full max-w-5xl px-4 py-8 md:px-8"><Unavailable /></main></DashboardLayout>;
  const catalogue = query.data;
  const categories = catalogue.categories as Category[];
  const products = catalogue.products as Product[];

  return <DashboardLayout><main className="mx-auto w-full max-w-6xl space-y-6 px-4 py-6 md:px-8 md:py-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge className="border-0 bg-slate-950 text-white hover:bg-slate-950"><LockKeyhole className="mr-1.5 h-3.5 w-3.5" /> Éditeur privé Studio</Badge><Badge variant="outline" className="border-teal-200 bg-teal-50 text-teal-950">Catalogue réel conservé</Badge></div><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Compléter le catalogue existant</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Le kit animalier est conservé. Vous pouvez enrichir ses fiches avec texte, prix, stock, images et variantes sans ouvrir la boutique au public.</p></div><Button type="button" variant="outline" onClick={() => setLocation(`/admin/studio/publication-catalogue/${storeId}`)} className="w-fit border-slate-300 bg-white text-slate-800 hover:bg-slate-50"><ArrowLeft className="mr-2 h-4 w-4" /> Publication contrôlée</Button></header>
    <section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5 text-sm leading-6 text-emerald-950"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="font-bold">{catalogue.store.displayName} reste protégée.</p><p className="mt-1">Les enregistrements de cette page ne rendent ni storefront, ni panier, ni checkout, ni paiement accessibles au public.</p></div></div></section>
    <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5"><Card className="border-slate-200 shadow-sm"><CardHeader className="border-b border-slate-100"><CardDescription>Base existante à préserver</CardDescription><CardTitle className="mt-1 text-xl">Catégories</CardTitle></CardHeader><CardContent className="space-y-4 p-5">{categories.map(category => <CategoryEditor key={category.id} category={category} pending={saveCategory.isPending} onSave={input => saveCategory.mutate({ storeId, ...input })} />)}</CardContent></Card>
        <Card className="border-slate-200 shadow-sm"><CardHeader className="border-b border-slate-100"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardDescription>Fiches réelles, non publiques</CardDescription><CardTitle className="mt-1 text-xl">Produits, images et variantes</CardTitle></div><Button type="button" onClick={() => setAddOpen(value => !value)} className="min-h-11 bg-teal-700 text-white hover:bg-teal-800"><PackagePlus className="mr-2 h-4 w-4" /> Ajouter une fiche</Button></div></CardHeader><CardContent className="space-y-5 p-5">{addOpen ? <NewProductEditor categories={categories} pending={createProduct.isPending} onCancel={() => setAddOpen(false)} onCreate={input => createProduct.mutate({ storeId, ...input })} /> : null}{products.map(product => <ProductEditor key={product.id} product={product} categories={categories} pending={saveProduct.isPending} uploadPending={uploadProductImage.isPending} onUpload={uploadImage} onSave={input => saveProduct.mutate({ storeId, productId: product.id, ...input })} />)}{!products.length ? <p className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm leading-6 text-slate-600">Aucune fiche réelle. Ajoutez une première fiche dans une catégorie existante.</p> : null}</CardContent></Card></div>
      <aside className="space-y-5"><Card className="border-amber-200 bg-amber-50"><CardContent className="p-5 text-sm leading-6 text-amber-950"><p className="flex items-center gap-2 font-bold"><PencilLine className="h-4 w-4" /> Portée de cet éditeur</p><p className="mt-2">Il enregistre texte, prix, stock, images et variantes client. Les fournisseurs, livraisons et paiements restent des étapes distinctes.</p></CardContent></Card><Card className="border-slate-200"><CardContent className="p-5 text-sm leading-6 text-slate-700"><p className="font-bold text-slate-950">Après vos modifications</p><p className="mt-2">Vérifiez la présentation dans l’aperçu privé. L’ouverture publique demeure une action distincte avec son prévol et une confirmation explicite.</p><Button type="button" variant="outline" className="mt-4 min-h-11 w-full border-slate-300" onClick={() => setLocation(`/admin/studio/apercu/${storeId}`)}>Voir l’aperçu privé</Button></CardContent></Card></aside>
    </section>
  </main></DashboardLayout>;
}

function CategoryEditor({ category, pending, onSave }: { category: Category; pending: boolean; onSave: (input: { categoryId: number; name: string; description: string }) => void }) {
  const [name, setName] = useState(category.name); const [description, setDescription] = useState(category.description || "");
  return <article className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="min-w-0 flex-1 space-y-2"><Label htmlFor={`category-name-${category.id}`}>Nom de catégorie</Label><Input id={`category-name-${category.id}`} value={name} onChange={event => setName(event.target.value)} /></div><Button type="button" disabled={pending || name.trim().length < 2} onClick={() => onSave({ categoryId: category.id, name: name.trim(), description: description.trim() })} className="min-h-11 bg-slate-900 text-white hover:bg-slate-800"><Save className="mr-2 h-4 w-4" /> Enregistrer</Button></div><div className="mt-3 space-y-2"><Label htmlFor={`category-description-${category.id}`}>Description</Label><Textarea id={`category-description-${category.id}`} value={description} onChange={event => setDescription(event.target.value)} rows={3} /></div><p className="mt-2 text-xs text-slate-500">Slug actuel : /{category.slug} — ajusté automatiquement si le nom change.</p></article>;
}

function ProductEditor({ product, categories, pending, uploadPending, onUpload, onSave }: { product: Product; categories: Category[]; pending: boolean; uploadPending: boolean; onUpload: (productId: number, file: File) => Promise<string>; onSave: (input: ProductInput) => void }) {
  const [categoryId, setCategoryId] = useState(String(product.categoryId)); const [name, setName] = useState(product.name); const [description, setDescription] = useState(product.description || ""); const [longDescription, setLongDescription] = useState(product.longDescription || ""); const [price, setPrice] = useState((product.price / 100).toFixed(2)); const [stock, setStock] = useState(String(product.stock)); const [featured, setFeatured] = useState(product.featured); const [images, setImages] = useState(product.images || []); const [options, setOptions] = useState(parseOptions(product.options));
  const priceCents = Math.round(Number(price.replace(",", ".")) * 100); const stockValue = Math.max(0, Math.round(Number(stock) || 0)); const valid = name.trim().length >= 2 && Number.isFinite(priceCents) && priceCents >= 0 && Number.isInteger(Number(categoryId));
  return <article className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-950">{product.name}</p><p className="mt-1 text-xs text-slate-500">/{product.slug} · statut {product.status}</p></div><Label className="flex cursor-pointer items-center gap-2 text-sm text-slate-700"><Checkbox checked={featured} onCheckedChange={value => setFeatured(value === true)} /> Mettre à la une</Label></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nom" id={`product-name-${product.id}`} value={name} setValue={setName} /><CategorySelect id={`product-category-${product.id}`} categories={categories} value={categoryId} setValue={setCategoryId} /><Field label="Prix CHF" id={`product-price-${product.id}`} value={price} setValue={setPrice} inputMode="decimal" /><Field label="Stock" id={`product-stock-${product.id}`} value={stock} setValue={setStock} inputMode="numeric" /></div><TextField label="Accroche / description courte" id={`product-description-${product.id}`} value={description} setValue={setDescription} rows={3} /><TextField label="Description détaillée" id={`product-long-description-${product.id}`} value={longDescription} setValue={setLongDescription} rows={5} /><MediaAndVariants productId={product.id} images={images} setImages={setImages} options={options} setOptions={setOptions} uploadPending={uploadPending} onUpload={onUpload} /><div className="mt-5 flex justify-end"><Button type="button" disabled={pending || !valid} onClick={() => onSave({ categoryId: Number(categoryId), name: name.trim(), description: description.trim(), longDescription: longDescription.trim(), priceCents, stock: stockValue, featured, images, options })} className="min-h-11 bg-slate-900 text-white hover:bg-slate-800"><Save className="mr-2 h-4 w-4" /> Enregistrer la fiche</Button></div></article>;
}

function NewProductEditor({ categories, pending, onCancel, onCreate }: { categories: Category[]; pending: boolean; onCancel: () => void; onCreate: (input: ProductInput) => void }) {
  const [categoryId, setCategoryId] = useState(String(categories[0]?.id || "")); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [longDescription, setLongDescription] = useState(""); const [price, setPrice] = useState(""); const [stock, setStock] = useState("0"); const [featured, setFeatured] = useState(false); const [options, setOptions] = useState<VariantOption[]>([]);
  const priceCents = Math.round(Number(price.replace(",", ".")) * 100); const valid = name.trim().length >= 2 && Number.isFinite(priceCents) && priceCents >= 1 && Number.isInteger(Number(categoryId));
  return <article className="rounded-2xl border border-teal-200 bg-teal-50 p-4"><div className="flex items-center justify-between"><p className="font-bold text-teal-950">Nouvelle fiche réelle</p><Button type="button" variant="ghost" onClick={onCancel}>Annuler</Button></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nom" id="new-product-name" value={name} setValue={setName} /><CategorySelect id="new-product-category" categories={categories} value={categoryId} setValue={setCategoryId} /><Field label="Prix CHF" id="new-product-price" value={price} setValue={setPrice} inputMode="decimal" /><Field label="Stock" id="new-product-stock" value={stock} setValue={setStock} inputMode="numeric" /></div><TextField label="Accroche / description courte" id="new-product-description" value={description} setValue={setDescription} rows={3} /><TextField label="Description détaillée" id="new-product-long-description" value={longDescription} setValue={setLongDescription} rows={5} /><Label className="mt-4 flex cursor-pointer items-center gap-2 text-sm text-teal-950"><Checkbox checked={featured} onCheckedChange={value => setFeatured(value === true)} /> Mettre à la une</Label><VariantEditor options={options} setOptions={setOptions} prefix="new" /><p className="mt-4 rounded-xl border border-teal-200 bg-white/70 p-3 text-sm leading-6 text-teal-950">Enregistrez d’abord la fiche, puis rouvrez-la pour téléverser ses images.</p><div className="mt-4 flex justify-end"><Button type="button" disabled={pending || !valid} onClick={() => onCreate({ categoryId: Number(categoryId), name: name.trim(), description: description.trim(), longDescription: longDescription.trim(), priceCents, stock: Math.max(0, Math.round(Number(stock) || 0)), featured, images: [], options })} className="min-h-11 bg-teal-700 text-white hover:bg-teal-800"><PackagePlus className="mr-2 h-4 w-4" /> Ajouter au catalogue</Button></div></article>;
}

function MediaAndVariants({ productId, images, setImages, options, setOptions, uploadPending, onUpload }: { productId: number; images: string[]; setImages: (value: string[]) => void; options: VariantOption[]; setOptions: (value: VariantOption[]) => void; uploadPending: boolean; onUpload: (productId: number, file: File) => Promise<string> }) {
  const [newImageUrl, setNewImageUrl] = useState(""); const [uploadError, setUploadError] = useState("");
  const addUrl = () => { const url = newImageUrl.trim(); if (url && (url.startsWith("/") || /^https:\/\//i.test(url)) && images.length < 8) { setImages([...images, url]); setNewImageUrl(""); } };
  const handleFile = async (file?: File) => { if (!file) return; setUploadError(""); try { const url = await onUpload(productId, file); if (!images.includes(url) && images.length < 8) setImages([...images, url]); } catch (error) { setUploadError(error instanceof Error ? error.message : "Téléversement impossible."); } };
  return <section className="mt-5 grid gap-5 border-t border-slate-100 pt-5 lg:grid-cols-2"><div><p className="text-sm font-bold text-slate-950">Images produit</p><p className="mt-1 text-xs leading-5 text-slate-500">La première image est l’image principale. Maximum 8, JPEG, PNG ou WebP.</p><div className="mt-3 flex gap-2"><Input value={newImageUrl} onChange={event => setNewImageUrl(event.target.value)} placeholder="https://… ou /media/…" /><Button type="button" variant="outline" disabled={!newImageUrl.trim() || images.length >= 8} onClick={addUrl}>Ajouter</Button></div><div className="mt-3 flex flex-wrap gap-3"><Label className="inline-flex min-h-11 cursor-pointer items-center rounded-md border border-input bg-white px-3 text-sm font-medium hover:bg-slate-50"><ImagePlus className="mr-2 h-4 w-4" /> {uploadPending ? "Téléversement…" : "Téléverser"}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" disabled={uploadPending || images.length >= 8} onChange={event => { void handleFile(event.target.files?.[0]); event.currentTarget.value = ""; }} /></Label></div>{uploadError ? <p className="mt-2 text-xs text-rose-700">{uploadError}</p> : null}<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{images.map((url, index) => <div key={`${url}-${index}`} className="relative overflow-hidden rounded-xl border border-slate-200 bg-slate-50"><img src={url} alt={`Visuel ${index + 1}`} className="h-24 w-full object-cover" /><div className="flex items-center gap-1 p-2"><Button type="button" size="icon" variant="outline" disabled={index === 0} title="Définir comme principale" onClick={() => setImages([images[index], ...images.filter((_, itemIndex) => itemIndex !== index)])}><ArrowUp className="h-3.5 w-3.5" /></Button><Button type="button" size="icon" variant="outline" title="Retirer" onClick={() => setImages(images.filter((_, itemIndex) => itemIndex !== index))}><X className="h-3.5 w-3.5" /></Button><span className="ml-auto text-[10px] font-semibold text-slate-500">{index === 0 ? "Principale" : `#${index + 1}`}</span></div></div>)}</div></div><div><VariantEditor options={options} setOptions={setOptions} prefix={`product-${productId}`} /></div></section>;
}

function VariantEditor({ options, setOptions, prefix }: { options: VariantOption[]; setOptions: (value: VariantOption[]) => void; prefix: string }) {
  const [name, setName] = useState(""); const [values, setValues] = useState("");
  const add = () => { const cleanName = name.trim(); const cleanValues = values.split(",").map(value => value.trim()).filter(Boolean).slice(0, 30); if (cleanName && cleanValues.length && options.length < 4) { setOptions([...options, { name: cleanName, values: cleanValues }]); setName(""); setValues(""); } };
  return <div><p className="text-sm font-bold text-slate-950">Variantes client</p><p className="mt-1 text-xs leading-5 text-slate-500">Ex. Couleur : Noir, Beige ; Taille : S, M, L. Sans lien fournisseur ni achat.</p><div className="mt-3 grid gap-2 sm:grid-cols-[minmax(0,0.7fr)_minmax(0,1fr)_auto]"><Input id={`${prefix}-variant-name`} value={name} onChange={event => setName(event.target.value)} placeholder="Nom, ex. Couleur" /><Input id={`${prefix}-variant-values`} value={values} onChange={event => setValues(event.target.value)} placeholder="Valeurs séparées par virgules" /><Button type="button" variant="outline" disabled={!name.trim() || !values.trim() || options.length >= 4} onClick={add}><Plus className="mr-1 h-4 w-4" /> Ajouter</Button></div><div className="mt-3 space-y-2">{options.map((option, index) => <div key={`${option.name}-${index}`} className="flex items-start justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div><p className="font-semibold text-slate-900">{option.name}</p><p className="mt-1 text-sm text-slate-600">{option.values.join(" · ")}</p></div><Button type="button" size="icon" variant="ghost" title="Retirer la variante" onClick={() => setOptions(options.filter((_, itemIndex) => itemIndex !== index))}><X className="h-4 w-4" /></Button></div>)}</div></div>;
}

function CategorySelect({ id, categories, value, setValue }: { id: string; categories: Category[]; value: string; setValue: (value: string) => void }) { return <div className="space-y-2"><Label htmlFor={id}>Catégorie</Label><select id={id} value={value} onChange={event => setValue(event.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choisir</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div>; }
function Field({ label, id, value, setValue, inputMode }: { label: string; id: string; value: string; setValue: (value: string) => void; inputMode?: "decimal" | "numeric" }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} value={value} inputMode={inputMode} onChange={event => setValue(event.target.value)} /></div>; }
function TextField({ label, id, value, setValue, rows }: { label: string; id: string; value: string; setValue: (value: string) => void; rows: number }) { return <div className="mt-4 space-y-2"><Label htmlFor={id}>{label}</Label><Textarea id={id} value={value} onChange={event => setValue(event.target.value)} rows={rows} /></div>; }
function parseOptions(raw: string | null): VariantOption[] { try { const parsed = raw ? JSON.parse(raw) : []; return Array.isArray(parsed) ? parsed.filter((item): item is VariantOption => Boolean(item && typeof item.name === "string" && Array.isArray(item.values))).slice(0, 4).map(item => ({ name: item.name.slice(0, 60), values: item.values.filter(value => typeof value === "string").map(value => value.slice(0, 60)).slice(0, 30) })).filter(item => item.name && item.values.length) : []; } catch { return []; } }
function readFileAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("Lecture de fichier impossible.")); reader.onerror = () => reject(new Error("Lecture de fichier impossible.")); reader.readAsDataURL(file); }); }
function Unavailable() { return <Card className="border-rose-200 bg-rose-50"><CardContent className="flex gap-3 p-5 text-sm leading-6 text-rose-950"><CircleAlert className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="font-semibold">Éditeur de catalogue indisponible.</p><p className="mt-1">Cette page est réservée aux boutiques offertes encore en préparation, depuis MAZIGHO Studio.</p></div></CardContent></Card>; }
