export const customCreationRequestKinds = ["portrait", "object", "animal", "home", "textile", "other"] as const;
export type CustomCreationRequestKind = (typeof customCreationRequestKinds)[number];

export const customCreationRequestStatuses = ["submitted", "in_review", "answered", "closed"] as const;
export type CustomCreationRequestStatus = (typeof customCreationRequestStatuses)[number];

export const CUSTOM_CREATION_REQUEST_LIMITS = {
  title: 140,
  description: 3_000,
  dimensions: 300,
  budget: 12,
  deadline: 10,
  ownerReply: 3_000,
  headline: 160,
  intro: 1_000,
  navigationLabel: 40,
} as const;

/** A concise decimal amount keeps briefs useful without turning them into a quote. */
export const CUSTOM_CREATION_REQUEST_BUDGET_PATTERN = /^(?:0|[1-9]\d{0,8})(?:[.,]\d{1,2})?$/;
const customCreationRequestDatePattern = /^\d{4}-\d{2}-\d{2}$/;

export function normalizeCustomCreationRequestBudget(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!CUSTOM_CREATION_REQUEST_BUDGET_PATTERN.test(trimmed)) return null;
  const normalized = trimmed.replace(",", ".");
  const amount = Number(normalized);
  return Number.isFinite(amount) && amount >= 0 ? normalized : null;
}

/** Accepts only a real ISO calendar date generated by the native date control. */
export function isCustomCreationRequestDeadline(value: unknown): value is string {
  if (typeof value !== "string" || !customCreationRequestDatePattern.test(value)) return false;
  const date = new Date(`${value}T12:00:00.000Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value;
}

export function formatCustomCreationRequestBudget(value: string, currencyCode: string, locale = "fr-CH") {
  const normalized = normalizeCustomCreationRequestBudget(value);
  if (!normalized) return value;
  try {
    return new Intl.NumberFormat(locale, { style: "currency", currency: currencyCode, currencyDisplay: "code", minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(Number(normalized));
  } catch {
    return `${normalized} ${currencyCode}`;
  }
}

export function formatCustomCreationRequestDeadline(value: string, locale = "fr-CH") {
  if (!isCustomCreationRequestDeadline(value)) return value;
  return new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(`${value}T12:00:00.000Z`));
}

export type StoreCustomCreationRequestSettings = {
  enabled: boolean;
  /** A boutique may accept briefs while keeping the public shortcut hidden. */
  visibleInNavigation: boolean;
  /** Short public shortcut text, adapted to the boutique's activity. */
  navigationLabel: string;
  headline: string;
  intro: string;
};

export const DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS: StoreCustomCreationRequestSettings = {
  enabled: false,
  visibleInNavigation: true,
  navigationLabel: "Sur mesure",
  headline: "Une demande à préparer ?",
  intro: "Expliquez ce dont vous avez besoin. La boutique vous répondra après étude, sans devis ni commande automatiques.",
};

export const customCreationRequestKindLabels: Record<CustomCreationRequestKind, string> = {
  portrait: "Personnalisation",
  object: "Produit ou article",
  animal: "Animal ou compagnon",
  home: "Maison ou décoration",
  textile: "Textile ou accessoire",
  other: "Autre demande",
};

export const customCreationRequestStatusPresentation: Record<CustomCreationRequestStatus, { label: string; detail: string; tone: "slate" | "amber" | "teal" | "violet" }> = {
  submitted: { label: "Envoyée", detail: "Votre demande attend une première lecture par la boutique.", tone: "slate" },
  in_review: { label: "En étude", detail: "La boutique examine votre demande. Aucun devis ni engagement n’est encore créé.", tone: "amber" },
  answered: { label: "Réponse disponible", detail: "La boutique a ajouté une réponse dans cet espace.", tone: "teal" },
  closed: { label: "Clôturée", detail: "Cette demande est clôturée. Vous pouvez en créer une autre si votre projet évolue.", tone: "violet" },
};

function readText(value: unknown, fallback: string, maximum: number) {
  return typeof value === "string" ? value.trim().slice(0, maximum) || fallback : fallback;
}

/** Invalid historical settings never activate a customer-facing workflow. */
export function parseStoreCustomCreationRequestSettings(value: string | null | undefined): StoreCustomCreationRequestSettings {
  if (!value) return { ...DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS };
  try {
    const parsed = JSON.parse(value) as Partial<StoreCustomCreationRequestSettings>;
    return {
      enabled: parsed.enabled === true,
      // Existing activated boutiques gain the useful shortcut by default; only
      // an explicit false hides it.
      visibleInNavigation: parsed.visibleInNavigation !== false,
      navigationLabel: readText(parsed.navigationLabel, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.navigationLabel, CUSTOM_CREATION_REQUEST_LIMITS.navigationLabel),
      headline: readText(parsed.headline, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.headline, CUSTOM_CREATION_REQUEST_LIMITS.headline),
      intro: readText(parsed.intro, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.intro, CUSTOM_CREATION_REQUEST_LIMITS.intro),
    };
  } catch {
    return { ...DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS };
  }
}

export function normalizeStoreCustomCreationRequestSettings(input: Partial<StoreCustomCreationRequestSettings>): StoreCustomCreationRequestSettings {
  return {
    enabled: input.enabled === true,
    visibleInNavigation: input.visibleInNavigation !== false,
    navigationLabel: readText(input.navigationLabel, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.navigationLabel, CUSTOM_CREATION_REQUEST_LIMITS.navigationLabel),
    headline: readText(input.headline, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.headline, CUSTOM_CREATION_REQUEST_LIMITS.headline),
    intro: readText(input.intro, DEFAULT_STORE_CUSTOM_CREATION_REQUEST_SETTINGS.intro, CUSTOM_CREATION_REQUEST_LIMITS.intro),
  };
}

export function getCustomCreationRequestStatusPresentation(status: string) {
  return customCreationRequestStatusPresentation[status as CustomCreationRequestStatus] || customCreationRequestStatusPresentation.submitted;
}

export function isCustomCreationRequestStatus(value: string): value is CustomCreationRequestStatus {
  return (customCreationRequestStatuses as readonly string[]).includes(value);
}
