import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Layers3, Loader2, ShieldCheck, Trash2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { saasPlanFeatureCatalog } from "@shared/saasPlanCatalog";
import type { StoreSaasPlanAssignment } from "@shared/storeSaasPlanAssignment";
import { toast } from "sonner";

type StorePlanTarget = {
  id: number;
  displayName: string;
  planAssignment: StoreSaasPlanAssignment | null;
  dropshippingAccess?: { enabled: boolean; source: "pro_plan" | "studio_grant" | "not_included" };
};

export default function StudioStorePlanAssignment({ store, onChanged }: { store: StorePlanTarget; onChanged: () => Promise<void> | void }) {
  const catalogQuery = trpc.admin.studio.getSaasPlanCatalog.useQuery(undefined, { refetchOnWindowFocus: false });
  const [planId, setPlanId] = useState("");
  const [confirmationName, setConfirmationName] = useState("");
  const [acknowledged, setAcknowledged] = useState(false);
  const [clearConfirmationName, setClearConfirmationName] = useState("");
  const [clearAcknowledged, setClearAcknowledged] = useState(false);
  const [dropshippingConfirmationName, setDropshippingConfirmationName] = useState("");
  const [dropshippingAcknowledged, setDropshippingAcknowledged] = useState(false);

  useEffect(() => {
    setPlanId(store.planAssignment?.planId ?? "");
    setConfirmationName("");
    setAcknowledged(false);
    setClearConfirmationName("");
    setClearAcknowledged(false);
    setDropshippingConfirmationName("");
    setDropshippingAcknowledged(false);
  }, [store.id, store.planAssignment?.planId]);

  const selectedTemplate = useMemo(() => catalogQuery.data?.plans.find(plan => plan.id === planId) ?? null, [catalogQuery.data?.plans, planId]);
  const assign = trpc.admin.studio.assignStoreSaasPlanTemplate.useMutation({
    onSuccess: async () => { toast.success("Plan commercial attribué. Les quotas, la commission Stripe et le verrou dropshipping sont recalculés pour cette boutique."); await onChanged(); },
    onError: error => toast.error(error.message || "Le plan n’a pas pu être attribué."),
  });
  const clear = trpc.admin.studio.clearStoreSaasPlanAssignment.useMutation({
    onSuccess: async () => { toast.success("Attribution de plan retirée. La boutique revient aux limites FREE, sans supprimer ses données existantes."); await onChanged(); },
    onError: error => toast.error(error.message || "L’attribution n’a pas pu être retirée."),
  });
  const setDropshippingAccess = trpc.admin.studio.setStoreDropshippingAccess.useMutation({
    onSuccess: async data => { toast.success(data.enabled ? "Accès dropshipping accordé à cette boutique." : "Accès dropshipping retiré."); await onChanged(); },
    onError: error => toast.error(error.message || "L’accès dropshipping n’a pas pu être modifié."),
  });
  const canAssign = Boolean(selectedTemplate && confirmationName.trim() === store.displayName.trim() && acknowledged);
  const canClear = Boolean(store.planAssignment && clearConfirmationName.trim() === store.displayName.trim() && clearAcknowledged);
  const canSetDropshipping = Boolean(dropshippingConfirmationName.trim() === store.displayName.trim() && dropshippingAcknowledged);
  const dropshippingAccess = store.dropshippingAccess ?? { enabled: false, source: "not_included" as const };

  return <Card className="border-sky-200"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-sky-700" /> Offre SaaS attribuée</CardTitle><CardDescription className="mt-2 max-w-3xl">Associez explicitement l’offre commerciale à cette boutique. Les quotas de catalogue, accès et médias, la commission Stripe et l’accès dropshipping sont appliqués côté serveur ; les autres promesses de l’offre restent documentées.</CardDescription></div><Badge variant="outline" className="w-fit border-sky-200 bg-sky-50 text-sky-900">Attribution réversible</Badge></div></CardHeader><CardContent className="space-y-4">{catalogQuery.isLoading ? <div className="h-36 animate-pulse rounded-xl bg-slate-100" /> : <><div className="rounded-xl border border-sky-100 bg-sky-50/60 p-4"><p className="text-xs font-bold uppercase tracking-wide text-sky-800">Attribution actuelle</p>{store.planAssignment ? <><div className="mt-2 flex flex-wrap items-center gap-2"><p className="text-lg font-bold text-slate-950">{store.planAssignment.planName}</p><Badge variant="outline" className="border-sky-200 bg-white text-sky-900">{store.planAssignment.features.length} fonctionnalité(s) proposées</Badge></div><p className="mt-2 text-xs leading-5 text-slate-600">Attribuée le {new Date(store.planAssignment.assignedAt).toLocaleString("fr-CH", { dateStyle: "medium", timeStyle: "short" })}. Cette copie reste stable même si le catalogue est modifié ensuite.</p>{store.planAssignment.lifetimePurchasePriceCents !== null && <p className="mt-2 rounded-lg border border-violet-200 bg-violet-50 p-3 text-sm font-semibold text-violet-950">Prix Lifetime figé : {(store.planAssignment.lifetimePurchasePriceCents / 100).toLocaleString("fr-CH", { style: "currency", currency: "CHF" })}. Ce snapshot ne crée encore aucun encaissement.</p>}</> : <p className="mt-2 text-sm leading-6 text-slate-700">Aucune offre n’est encore attribuée à cette boutique.</p>}</div>
    {store.planAssignment && <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-600">Fonctionnalités de l’offre attribuée</p><p className="mt-1 text-sm leading-6 text-slate-700">Copie attribuée : {store.planAssignment.features.length}/{saasPlanFeatureCatalog.length} fonctionnalité(s). Les quotas, la commission Stripe et le verrou dropshipping sont appliqués ; les autres éléments ci-dessous restent le périmètre commercial de l’offre.</p></div><Badge variant="outline" className="w-fit border-slate-200 bg-slate-50 text-slate-700">Snapshot stable</Badge></div><div className="mt-4 grid gap-2 lg:grid-cols-2">{saasPlanFeatureCatalog.map(feature => { const included = store.planAssignment!.features.includes(feature.id); return <div key={feature.id} className={`rounded-lg border p-3 ${included ? "border-emerald-200 bg-emerald-50/60" : "border-slate-200 bg-slate-50"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-950">{feature.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{feature.description}</p></div><Badge variant="outline" className={included ? "shrink-0 border-emerald-200 bg-white text-emerald-800" : "shrink-0 border-slate-200 bg-white text-slate-600"}>{included ? "Incluse" : "Non incluse"}</Badge></div></div>; })}</div></section>}
    <section className="rounded-xl border border-amber-200 bg-amber-50/70 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-amber-900">Accès dropshipping</p><p className="mt-1 text-sm leading-6 text-amber-950">{dropshippingAccess.source === "pro_plan" ? "Inclus par l’offre PRO : import fournisseur en brouillon, avec validation manuelle avant publication." : dropshippingAccess.source === "studio_grant" ? "Accordé par dérogation Studio à cette boutique. Cela ne crée aucun fournisseur, aucune commande automatique ni aucun prélèvement." : "Réservé à l’offre PRO. Vous pouvez toutefois l’accorder manuellement à cette boutique précise."}</p></div><Badge variant="outline" className={dropshippingAccess.enabled ? "w-fit border-emerald-200 bg-white text-emerald-800" : "w-fit border-amber-200 bg-white text-amber-900"}>{dropshippingAccess.source === "pro_plan" ? "Inclus PRO" : dropshippingAccess.source === "studio_grant" ? "Dérogation Studio" : "Verrouillé"}</Badge></div>{dropshippingAccess.source !== "pro_plan" && <div className="mt-4 space-y-3 border-t border-amber-200 pt-4"><div className="space-y-2"><Label htmlFor={`store-dropshipping-confirmation-${store.id}`}>Recopiez le nom de la boutique</Label><Input id={`store-dropshipping-confirmation-${store.id}`} value={dropshippingConfirmationName} onChange={event => setDropshippingConfirmationName(event.target.value)} placeholder={store.displayName} /></div><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-amber-200 bg-white p-3 text-sm leading-6 text-amber-950"><Checkbox checked={dropshippingAcknowledged} onCheckedChange={value => setDropshippingAcknowledged(value === true)} className="mt-1" /><span>Je confirme {dropshippingAccess.enabled ? "retirer" : "accorder"} seulement l’accès au module dropshipping pour <strong>{store.displayName}</strong>. Aucun plan, fournisseur, produit, paiement ou automatisation n’est créé.</span></label><Button type="button" variant={dropshippingAccess.enabled ? "outline" : "default"} className={dropshippingAccess.enabled ? "min-h-11 w-full border-amber-300 bg-white text-amber-950 hover:bg-amber-100" : "min-h-11 w-full bg-amber-700 hover:bg-amber-800"} disabled={!canSetDropshipping || setDropshippingAccess.isPending} onClick={() => setDropshippingAccess.mutate({ storeId: store.id, confirmationName: dropshippingConfirmationName, enabled: !dropshippingAccess.enabled, acknowledged: true })}>{setDropshippingAccess.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Enregistrement…</> : dropshippingAccess.enabled ? "Retirer la dérogation Studio" : "Accorder le dropshipping à cette boutique"}</Button></div>}</section>
    <div className="space-y-2"><Label htmlFor={`store-plan-template-${store.id}`}>Modèle à attribuer</Label><Select value={planId} onValueChange={setPlanId}><SelectTrigger id={`store-plan-template-${store.id}`} className="min-h-11 bg-white"><SelectValue placeholder="Choisir une offre du catalogue" /></SelectTrigger><SelectContent>{catalogQuery.data?.plans.map(plan => <SelectItem key={plan.id} value={plan.id}>{plan.name} · {plan.features.length} fonctionnalité(s)</SelectItem>)}</SelectContent></Select></div>
    {selectedTemplate && <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-950">{selectedTemplate.name}</p><p className="mt-1 text-xs leading-5 text-slate-600">{selectedTemplate.description}</p><div className="mt-3 flex flex-wrap gap-2">{selectedTemplate.features.map(featureId => <Badge key={featureId} variant="outline" className="border-slate-200 bg-white text-slate-700">{saasPlanFeatureCatalog.find(feature => feature.id === featureId)?.title || featureId}</Badge>)}</div></div>}
    <div className="space-y-2"><Label htmlFor={`store-plan-confirmation-${store.id}`}>Recopiez le nom de la boutique</Label><Input id={`store-plan-confirmation-${store.id}`} value={confirmationName} onChange={event => setConfirmationName(event.target.value)} placeholder={store.displayName} /></div><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm leading-6 text-slate-700"><Checkbox checked={acknowledged} onCheckedChange={value => setAcknowledged(value === true)} className="mt-1" /><span>Je confirme attribuer cette offre à <strong>{store.displayName}</strong>. Les quotas, la commission Stripe et l’accès dropshipping seront recalculés ; aucun encaissement, e-mail, facture, fournisseur ou statut de boutique n’est créé.</span></label><Button type="button" className="min-h-11 w-full bg-sky-700 hover:bg-sky-800" disabled={!canAssign || assign.isPending} onClick={() => assign.mutate({ storeId: store.id, confirmationName, planId, acknowledged: true })}>{assign.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Attribution…</> : <><CheckCircle2 className="mr-2 h-4 w-4" />Attribuer l’offre</>}</Button>
    {store.planAssignment && <div className="border-t border-slate-200 pt-5"><p className="font-semibold text-slate-950">Revenir à FREE</p><p className="mt-1 text-xs leading-5 text-slate-600">Cela retire le snapshot commercial et restaure les limites FREE. Aucune donnée existante, commande, facture ou abonnement n’est supprimé.</p><div className="mt-3 space-y-2"><Label htmlFor={`store-plan-clear-${store.id}`}>Recopiez le nom de la boutique</Label><Input id={`store-plan-clear-${store.id}`} value={clearConfirmationName} onChange={event => setClearConfirmationName(event.target.value)} placeholder={store.displayName} /></div><label className="mt-3 flex cursor-pointer items-start gap-3 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm leading-6 text-rose-950"><Checkbox checked={clearAcknowledged} onCheckedChange={value => setClearAcknowledged(value === true)} className="mt-1" /><span>Je confirme restaurer les limites FREE pour cette boutique. Son catalogue déjà existant est conservé, mais les nouvelles créations seront soumises aux quotas FREE.</span></label><Button type="button" variant="outline" className="mt-3 min-h-11 w-full border-rose-200 bg-white text-rose-800 hover:bg-rose-50" disabled={!canClear || clear.isPending} onClick={() => clear.mutate({ storeId: store.id, confirmationName: clearConfirmationName, acknowledged: true })}>{clear.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Retrait…</> : <><Trash2 className="mr-2 h-4 w-4" />Restaurer FREE</>}</Button></div>}
    <div className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3 text-xs leading-5 text-slate-700"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-slate-600" /><p><strong>Application réelle :</strong> les quotas produits, accès délégués, médias, commission Stripe et verrou dropshipping sont déjà isolés et appliqués par boutique. Les autres fonctionnalités listées sont des promesses de plan à construire module par module avec tests d’isolation.</p></div></>}</CardContent></Card>;
}
